### ISSUE TITLE
Why mock server ignore empty strings

### ISSUE THREAD

**Issue by grvldmr** [mock-server/mockserver#802] opened 2020-06-19 21:39 UTC
**Describe the issue**
Server ignore empty string in response and does not return it.

**What you are trying to do**
Trying to send empty string in response.

**MockServer version**
5.8.0

**To Reproduce**
I am initializing response from initializerJson. After request, response doesn't have prop with empty value.

1. How you are running MockServer (i.e maven plugin, docker, etc)
Docker - mockserver/mockserver:mockserver-5.8.0
2. Code you used to create expectations
Examples from https://www.mock-server.com/
3. What error you saw
Doesn't have any.

**Expected behaviour**
In response should be json property with empty string like 
```
{
   "emptyStringProp": ""
}
```

**MockServer Log**
```
"body" : {
  "type" : "JSON",
   "json" : "{}"
 }
```

**Comment by jamesdbloom** [comment] 2020-06-20 09:26
I have an idea where this issue is but can you give a code example including the expectations you are setting and the request you are sending so that I can ensure I fix the issue correctly.

**Comment by jamesdbloom** [comment] 2020-06-20 09:28
It is likely caused by the same Jackson ObjectMapper being using for JSON bodies as is used for the MockServer control plane.  The control plane and logs should have blank and empty fields removed for simplicity and readability however response bodies should not.

**Comment by jamesdbloom** [comment] 2020-06-20 10:11
I've fixed it in the SNAPSHOT release but I still need to add some extra tests to avoid any future regression.

**Comment by jamesdbloom** [comment] 2020-06-21 09:08
I've added the integration tests, closing the issue

**Closed by jamesdbloom** 2020-06-21 09:08 UTC

**Comment by grvldmr** [comment] 2020-06-23 17:21
Thank you. It helped me a lot.
