### ISSUE TITLE
404 for same expectation during concurrent calls

### ISSUE THREAD

**Issue by BlitzFis** [mock-server/mockserver#901] opened 2020-10-26 20:00 UTC
**MockServer version**
5.11.1

**Expected behavior:**

When calling multiple time the mock server with the same payload, the response should be the same.

**Actual behavior:**

If multiples clients (or parallel calls) are hiring the mock server at the same time,  it can sometime return a "404"

**Analysis:**
When looking at the log it seems that it is not comparing the request with all the expectations and return sometime:
the "No expectation found" and the 404 HTTP Code

Reproducibility:

Using Jmeter (or another tool) and at least 2 parallels calls to 2 difference expectations will generate randomly some 404

```
      "X-API-KEY" : [ "bqqH6qdvhNWvZSAm3xlYp3IGHYQ9La64" ]
    },
    "keepAlive" : false,
    "secure" : false,
    "body" : "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">\n  <soap:Header/>\n  <soap:Body>\n    <ns1:SearchContractsRequest xmlns:ns1=\"http://www.cassiopae.com/back/contract/contractsearch/schema\">\n      <context/>\n      <contractsearchvo>\n        <dosid>16607</dosid>\n      </contractsearchvo>\n    </ns1:SearchContractsRequest>\n  </soap:Body>\n</soap:Envelope>"
  }

 returning response:

  {
    "statusCode" : 404,
    "reasonPhrase" : "Not Found"
  }

2020-10-26 20:50:37 5.11.1 PRÉCIS 8081 disconnected and closed socket /127.0.0.1:8081
```

**Comment by BlitzFis** [comment] 2020-10-26 21:34
Edit: I can see that sometime if 2 simultaneous request are hiring the server at the exact same time, there is a chance that the expectation got exchanged when the response is returned , so the issue is not only 404.

**Comment by jamesdbloom** [comment] 2020-11-08 04:49
This is strange because MockServer has numerous performance tests that confirm in the scenarios tested this is not happening.  Can you please provide details of the exact expectations you are creating so I can reproduce this test.

**Comment by jamesdbloom** [comment] 2022-01-17 13:13
Closing due to lack of information / activity

**Closed by jamesdbloom** 2022-01-17 13:13 UTC
Labels: need_more_information, next
