### ISSUE TITLE
Error processing request: `"mockServerLogger" is null`

### ISSUE THREAD

**Issue by codan84** [mock-server/mockserver#1393] opened 2022-07-08 17:12 UTC
**Describe the issue**
Getting `SEVERE` exception whilst processing a request:
```
Cannot invoke "org.mockserver.logging.MockServerLogger.logEvent(org.mockserver.log.model.LogEntry)" because "mockServerLogger" is null +0ms
  java.lang.NullPointerException: Cannot invoke "org.mockserver.logging.MockServerLogger.logEvent(org.mockserver.log.model.LogEntry)" because "mockServerLogger" is null +0ms
  at org.mockserver.matchers.RegexStringMatcher.matchesByStrings(RegexStringMatcher.java:100) +0ms
  at org.mockserver.matchers.RegexStringMatcher.matchesByNottedStrings(RegexStringMatcher.java:73) +0ms
  at org.mockserver.matchers.RegexStringMatcher.matches(RegexStringMatcher.java:63) +0ms
  at org.mockserver.matchers.RegexStringMatcher.matches(RegexStringMatcher.java:52) +0ms
  at org.mockserver.collections.SubSetMatcher.matchesIndexes(SubSetMatcher.java:41) +0ms
  at org.mockserver.collections.SubSetMatcher.containsSubset(SubSetMatcher.java:18) +0ms
  at org.mockserver.collections.NottableStringMultiMap.containsAll(NottableStringMultiMap.java:52) +0ms
  at org.mockserver.matchers.MultiValueMapMatcher.matches(MultiValueMapMatcher.java:50) +0ms
  at org.mockserver.matchers.ParameterStringMatcher.matches(ParameterStringMatcher.java:31) +1ms
  at org.mockserver.matchers.ParameterStringMatcher.matches(ParameterStringMatcher.java:12) +0ms
  at org.mockserver.matchers.HttpRequestPropertiesMatcher.matches(HttpRequestPropertiesMatcher.java:472) +0ms
  at org.mockserver.matchers.HttpRequestPropertiesMatcher.bodyMatches(HttpRequestPropertiesMatcher.java:458) +0ms
  at org.mockserver.matchers.HttpRequestPropertiesMatcher.bodyMatches(HttpRequestPropertiesMatcher.java:418) +0ms
  at org.mockserver.matchers.HttpRequestPropertiesMatcher.matches(HttpRequestPropertiesMatcher.java:284) +0ms
  at org.mockserver.matchers.HttpRequestPropertiesMatcher.matches(HttpRequestPropertiesMatcher.java:202) +0ms
  at org.mockserver.mock.RequestMatchers.lambda$firstMatchingExpectation$9(RequestMatchers.java:226) +0ms
  at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) +0ms
  at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) +0ms
  at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) +0ms
  at java.base/java.util.concurrent.ConcurrentSkipListMap$KeySpliterator.tryAdvance(ConcurrentSkipListMap.java:3176) +0ms
  at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) +0ms
  at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) +0ms
  at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) +0ms
  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) +0ms
  at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) +0ms
  at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) +0ms
  at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) +0ms
  at org.mockserver.mock.RequestMatchers.firstMatchingExpectation(RequestMatchers.java:241) +0ms
  at org.mockserver.mock.HttpState.firstMatchingExpectation(HttpState.java:269) +0ms
  at org.mockserver.mock.action.http.HttpActionHandler.processAction(HttpActionHandler.java:95) +1ms
  at org.mockserver.netty.HttpRequestHandler.channelRead0(HttpRequestHandler.java:167) +0ms
  at org.mockserver.netty.HttpRequestHandler.channelRead0(HttpRequestHandler.java:48) +0ms
  at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) +0ms
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) +0ms
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) +0ms
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) +0ms
  at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) +0ms
  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) +0ms
  at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) +0ms
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) +0ms
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) +0ms
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) +0ms
  at org.mockserver.dashboard.DashboardWebSocketHandler.channelRead(DashboardWebSocketHandler.java:137) +0ms
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) +0ms
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) +0ms
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) +0ms
  at org.mockserver.netty.websocketregistry.CallbackWebSocketServerHandler.channelRead(CallbackWebSocketServerHandler.java:57) +1ms
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) +0ms
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) +0ms
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) +0ms
  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) +0ms
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) +0ms
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) +0ms
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) +0ms
  at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) +0ms
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) +0ms
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) +0ms
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) +0ms
  at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) +0ms
  at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) +0ms
  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) +0ms
  at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) +1ms
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) +0ms
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) +0ms
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) +0ms
  at org.mockserver.netty.unification.PortUnificationHandler.switchToHttp(PortUnificationHandler.java:257) +0ms
  at org.mockserver.netty.unification.PortUnificationHandler.decode(PortUnificationHandler.java:138) +0ms
  at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) +0ms
  at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366) +0ms
  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) +0ms
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) +0ms
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) +0ms
  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) +0ms
  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) +0ms
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) +1ms
  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) +0ms
  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) +0ms
  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) +0ms
  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) +0ms
  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) +0ms
  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) +0ms
  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) +0ms
  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) +0ms
  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) +0ms
  at java.base/java.lang.Thread.run(Thread.java:833) 
```

**What you are trying to do**
MockServer Server is trying to match a n incoming request. there are few expectations set and 1 of them supposed to be a match. However, it never gets to that particular one as it errors on one of the previous ones.

**MockServer version**
5.13.2 (Docker)

**To Reproduce**
Steps to reproduce the issue:

1. How you are running MockServer: docker
2. Code you used to create expectations: npm module
3. What error you saw: stack trace above

**Expected behaviour**
Request is matched against expectation and response returned.
```

**MockServer Log**
Log output, as INFO level (or lower)

**Comment by codan84** [comment] 2022-07-11 08:51
Just as additional info, after switching to version `5.12.0` of mockserver everything works as expected

**Comment by jamesdbloom** [comment] 2022-08-15 11:59
Can you please provide a way to reproduce this.  I can fix the null pointer exception in this exact stracktrace but it would be helpful to ensure I have fixed this everywhere for which I need a way to reproduce your issue.

**Comment by olivierACRI** [comment] 2022-08-16 11:42
looks like this one https://github.com/mock-server/mockserver/issues/1432

**Comment by jamesdbloom** [comment] 2022-08-17 12:42
This is now fixed and will be released in next week or so

**Closed by jamesdbloom** 2022-08-17 12:42 UTC
Labels: in progress, need_more_information
