### ISSUE TITLE
Java - Spring 5 WebClient support for MockClient proxy

### ISSUE THREAD

**Issue by northernbird** [mock-server/mockserver#812] opened 2020-07-12 13:06 UTC
**Describe the issue**
I would like to use MockServer as a proxy. Our web client implementation is based on Spring 5 WebClient. 
First, I tried to find the example for proxy configuration [here](https://mock-server.com/proxy/configuring_sut.html#web_secure_web_proxy), I can't find any example for WebClient.
Then by referring to the documentation above, I tried to implement it. However, it didn' work correctly. I get the following exception :
```
reactor.core.Exceptions$ReactiveException: reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		... 29 more
```

It would be nice if you could 
- Add the sample proxy implementation for WebClient
  - **I tested with [Java JDK HttpURLConnection (HTTP)](https://mock-server.com/proxy/configuring_sut.html#java_jdk_http_url_connection), it works fine. So I'm wondering there is any differences between WebClient & another sample implementations** 
- Make sure it works with WebClient

**What you are trying to do**
I would like to make mock server work as a proxy of WebClient (like:[Java JDK HttpURLConnection (HTTP)](https://mock-server.com/proxy/configuring_sut.html#java_jdk_http_url_connection).

**MockServer version**
5.11.0

**To Reproduce**
1. Initialize and start MockServer as a proxy. Like:
```
proxy = startClientAndServer(1090);
```
2. Set proxy values from 1. Like:
```
HttpClient httpClient = HttpClient.create()
            .tcpConfiguration(tcpClient -> tcpClient
                .proxy(proxy -> proxy
                    .type(ProxyProvider.Proxy.HTTP)
                    .host("localhost")
                    .port(1090)));

ReactorClientHttpConnector connector = new ReactorClientHttpConnector(httpClient);

WebClient webClient = WebClient.builder()
        .clientConnector(connector)
        .baseUrl("http://localhost:1080)
        .build();
```

**Expected behaviour**
Same as **What you are trying to do**

**MockServer Log**
N/A

**Comment by jamesdbloom** [comment] 2020-07-12 19:28
I'll take a look the proxy should work with WebClient because MockServer supports all the standard proxy techniques.  I'm happy to take a look at create an example.  I think it would be fair to say if it doesn't work with WebClient then that would most likely be a bug in WebClient.  All other HTTP Java clients tested >6 all work without any issue and other non-java clients such as Chrome, Firefox, Safari, OSX, Linux, VMWare, Curl, etc.

**Comment by northernbird** [comment] 2020-07-12 22:50
@jamesdbloom 

Thanks a lot for the support! I look forward to your feedback & answer.
Here is my sample test implementation. It might help you...
https://gist.github.com/northernbird/0576c43968454f71622bfd3674a623cf

There are two tests:
- `testProxyWithHttpURLConnection` : the test is based on [Java JDK HttpURLConnection (HTTP)](https://mock-server.com/proxy/configuring_sut.html#java_jdk_http_url_connection) and it works fine.
- `testProxyWithWebClient`: It's not working due to the following error :
```
reactor.core.Exceptions$ReactiveException: reactor.netty.http.client.PrematureCloseException: Connection prematurely closed BEFORE response

	at reactor.core.Exceptions.propagate(Exceptions.java:393)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
	at reactor.core.publisher.Mono.block(Mono.java:1679)
```

**Comment by northernbird** [comment] 2020-07-14 13:18
@jamesdbloom

I would like to share a few more debug information.
I suspect that this issue happens only in the specific situation under the usage of MockServer Proxy + WebClient.
As you commented, if I use MockServer Proxy with the different HTTP client implementation or WebClient with the other proxy server (like Squid proxy etc..) there is no problem.

Also, there are already several GitHub issues reported for a very similar case of ours.
- https://github.com/reactor/reactor-netty/issues/498
- https://github.com/reactor/reactor-netty/issues/796
- https://github.com/spring-projects/spring-framework/issues/22464
- https://github.com/reactor/reactor-netty/issues/632
- https://github.com/netty/netty/pull/8924
- https://github.com/reactor/reactor-netty/issues/1038

**Here is the stack trace of WebClient + MockServer Proxy:**

```
19:15:39.722 [reactor-http-nio-1] DEBUG reactor.netty.http.client.HttpClient - [id: 0xbe85715e, L:/127.0.0.1:65404 - R:localhost/127.0.0.1:1090] READ COMPLETE
19:15:39.727 [reactor-http-nio-1] DEBUG reactor.netty.resources.PooledConnectionProvider - [id: 0xbe85715e, L:/127.0.0.1:65404 ! R:localhost/127.0.0.1:1090] Channel closed, now 0 active connections and 0 inactive connections
19:15:39.727 [reactor-http-nio-1] DEBUG reactor.netty.ReactorNetty - [id: 0xbe85715e, L:/127.0.0.1:65404 ! R:localhost/127.0.0.1:1090] Non Removed handler: ReadTimeoutHandler, context: ChannelHandlerContext(ReadTimeoutHandler, [id: 0xbe85715e, L:/127.0.0.1:65404 ! R:localhost/127.0.0.1:1090]), pipeline: DefaultChannelPipeline{(HttpProxyHandler$HttpClientCodecWrapper#0 = io.netty.handler.proxy.HttpProxyHandler$HttpClientCodecWrapper), (reactor.left.proxyLoggingHandler = io.netty.handler.logging.LoggingHandler), (reactor.left.proxyHandler = io.netty.handler.proxy.HttpProxyHandler), (reactor.left.loggingHandler = io.netty.handler.logging.LoggingHandler), (reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (ReadTimeoutHandler = io.netty.handler.timeout.ReadTimeoutHandler), (WriteTimeoutHandler = io.netty.handler.timeout.WriteTimeoutHandler), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
19:15:39.727 [reactor-http-nio-1] DEBUG reactor.netty.ReactorNetty - [id: 0xbe85715e, L:/127.0.0.1:65404 ! R:localhost/127.0.0.1:1090] Non Removed handler: WriteTimeoutHandler, context: ChannelHandlerContext(WriteTimeoutHandler, [id: 0xbe85715e, L:/127.0.0.1:65404 ! R:localhost/127.0.0.1:1090]), pipeline: DefaultChannelPipeline{(HttpProxyHandler$HttpClientCodecWrapper#0 = io.netty.handler.proxy.HttpProxyHandler$HttpClientCodecWrapper), (reactor.left.proxyLoggingHandler = io.netty.handler.logging.LoggingHandler), (reactor.left.proxyHandler = io.netty.handler.proxy.HttpProxyHandler), (reactor.left.loggingHandler = io.netty.handler.logging.LoggingHandler), (reactor.left.httpCodec =
```

**Header difference between WebClient & Java HttpClient**

**WebClient/Netty**
```
{
    "method" : "GET",
    "path" : "/test",
    "headers" : {
      "user-agent" : [ "ReactorNetty/0.9.8.RELEASE" ],
      "host" : [ "localhost:1080" ],
      "Content-Type" : [ "application/json" ],
      "Accept" : [ "application/json" ],
      "Proxy-Connection" : [ "keep-alive" ],
      "Connection" : [ "keep-alive" ],
      "Keep-Alive" : [ "timeout=5, max=1000" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  }
```

**Java JDK HttpURLConnection (HTTP)**
```
{
    "method" : "GET",
    "path" : "/test",
    "headers" : {
      "User-Agent" : [ "Java/1.8.0_232" ],
      "Host" : [ "localhost:1080" ],
      "Accept" : [ "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2" ],
      "Proxy-Connection" : [ "keep-alive" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  }
```

**Comment by jamesdbloom** [comment] 2020-07-20 06:36
As soon as I've done the next release with some important fixes I'll look at this, likely end of this week or early next week.

**Comment by mprokopiukWR** [comment] 2020-08-20 12:56
Hi, any updates?

**Comment by northernbird** [comment] 2020-08-24 01:49
I would also like to know about updates.

**Comment by devansh-dalal** [comment] 2020-11-21 13:39
any updates on this?

**Comment by ZoeShaw101** [comment] 2021-04-06 16:12
same error here, any updates on this?

**Comment by Bragolgirith** [comment] 2021-04-14 19:20
This is probably due to a faulty netty pooling implementation. There were a couple of similar issues that were supposedly fixed in reactor-netty 0.9.x, but I'm still getting errors even on reactor-netty 1.0.5. 
The issue is hard to reproduce, since it seems to happen only under pressure, and only against some servers. 
What will probably help is using `HttpClient.newConnection()` instead of `HttpClient.create()` in order to prevent netty from using a connection pool. (I wouldn't recommend it for production though).

**Comment by MrZhengliang** [comment] 2021-12-01 05:21
same error here, any updates on this?

**Comment by mihaidi** [comment] 2022-01-26 06:21
Any updates, facing this issue and despite of huge nr of related issues none of them have a solution ?

**Comment by jamesdbloom** [comment] 2022-01-28 15:01
Sadly as usual Spring code is overly complex mess and some of the hardest code around to debug.  It is clear that the handling of TSL is not correct when TLS is disabled it still does encryption but in an invalid way so there is no way to disable TLS support.  Having said that I do have a working example with TLS.  

Unfortunately the Spring client also messes with the logging settings and some how prevents the standard JDK logger from ever logging FINEST / TRACE level so it is pretty hard to accurately debug what is going on.

Spring also seems to be doing something weird with tcnative that I can't work out.  I've tried everything reasonable around excluding dependencies in ever possible way i.e. from Spring, from MockServer, from Netty, etc, etc.  I suspect one of the dependencies has done some shading or something like that to make it effectively impossible to resolve the error about tcnative.  Luckily MockServer has a fallback which works fine.

I'll add a working example to mockserver-examples shortly once I've tied up the code.

**Closed** 2022-01-28 17:30 UTC
Labels: enhancement, documentation, next

**Comment by jamesdbloom** [comment] 2022-01-28 17:33
Please see example code committed here:
