### ISSUE TITLE
No matching by query string parameters using lists

### ISSUE THREAD

**Issue by AlexRuiz7** [mock-server/mockserver#1259] opened 2022-04-01 10:16 UTC
**Describe the issue**
It looks like the MockServer fails to match any request that use lists on the query string params.

I'm running tests on Postman and I saw that any requests that uses a list on its query paramaters fails with a 404 status code, so the MockServer didn't match any expectations but should.

Example:

`/agents?pretty=false&wait_for_complete=false&agents_list=002&offset=0&limit=500&select=<names>`

This endpoint has several query parameters. Only `agents_list` and `select` accept arrays as values, and these two are the only ones not matching on the MockServer.

`/agents` : matches the expectation
`/agents?pretty=true` : matches the expectation
`/agents?agents_list=000` : does not match the expectation

![image](https://user-images.githubusercontent.com/15186973/161108736-148b8ca0-4f19-4681-bdac-26c6304c0cbb.png)

**What you are trying to do**
I'm using the MockServer with an OpenAPI specification.

**MockServer version**
5.13.0

**To Reproduce**
Steps to reproduce the issue:

I attached the `docker-compose`, `intializer.json` and OpenAPI spec files used.
[mock.zip](https://github.com/mock-server/mockserver/files/8396777/mock.zip)

1. Setup the environment with `docker-compose up -d`
2. Perform some requests to the MockServer, either using any OpenAPI tool or using cURL:
    This works:
    ```bash
    curl -s -X GET 'http://localhost:55000/agents?limit=500' \
    -H 'Accept: application/json' \
    -H 'Authorization: Bearer <generated_token>'
    ```
    This does not (404):
    ```bash
    curl -s -X GET 'http://localhost:55000/agents?agents_list=000' \
    -H 'Accept: application/json' \
    -H 'Authorization: Bearer <generated_token>'
    ```
    Note that `agents_list` can contain several values: `?agents_list=000,001,002`
3. Check the logs at the dashboards. Search the operationId `api.controllers.agent_controller.get_agents`
4. Expand the log to see the reason why it didn't match.

**Expected behaviour**
What you expected to happen

**MockServer Log**
DEBUG

<summary>
This is the reason given by the MockServer for not matching the correct expectation:
</summary>

<details>

```
queryParameters didn't match: 
  multimap subset match failed expected:
    {
      "keyMatchStyle" : "MATCHING_KEY",
      "?wait_for_complete" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "default" : false,
            "type" : "boolean"
          }
        } ]
      },
      "?version" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "format" : "alphanumeric",
            "type" : "string"
          }
        } ]
      },
      "?status" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "items" : {
              "enum" : [ "active", "pending", "never_connected", "disconnected" ],
              "type" : "string"
            },
            "minItems" : 1,
            "type" : "array"
          }
        } ]
      },
      "?sort" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "format" : "sort",
            "type" : "string"
          }
        } ]
      },
      "?select" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "items" : {
              "format" : "names",
              "type" : "string"
            },
            "type" : "array"
          }
        } ]
      },
      "?search" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "format" : "search",
            "type" : "string"
          }
        } ]
      },
      "?registerIP" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "format" : "alphanumeric",
            "type" : "string"
          }
        } ]
      },
      "?q" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "type" : "string"
          }
        } ]
      },
      "?pretty" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "default" : false,
            "type" : "boolean"
          }
        } ]
      },
      "?os.version" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "format" : "alphanumeric",
            "type" : "string"
          }
        } ]
      },
      "?os.platform" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "format" : "alphanumeric",
            "type" : "string"
          }
        } ]
      },
      "?os.name" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "format" : "alphanumeric",
            "type" : "string"
          }
        } ]
      },
      "?older_than" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "format" : "timeframe",
            "type" : "string"
          }
        } ]
      },
      "?offset" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "default" : 0,
            "format" : "int32",
            "minimum" : 0,
            "type" : "integer"
          }
        } ]
      },
      "?node_name" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "format" : "names",
            "type" : "string"
          }
        } ]
      },
      "?name" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "format" : "alphanumeric",
            "type" : "string"
          }
        } ]
      },
      "?manager" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "format" : "alphanumeric",
            "type" : "string"
          }
        } ]
      },
      "?limit" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "default" : 500,
            "format" : "int32",
            "maximum" : 100000.0,
            "minimum" : 1,
            "type" : "integer"
          }
        } ]
      },
      "?ip" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "format" : "alphanumeric",
            "type" : "string"
          }
        } ]
      },
      "?group_config_status" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "enum" : [ "synced", "not synced" ],
            "type" : "string"
          }
        } ]
      },
      "?group" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "description" : "Group name",
            "format" : "group_names",
            "type" : "string"
          }
        } ]
      },
      "?agents_list" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "items" : {
              "description" : "Agent ID",
              "format" : "numbers",
              "minLength" : 3,
              "type" : "string"
            },
            "type" : "array"
          }
        } ]
      }
    }
   found:
    {
      "agents_list" : [ "002" ]
    }
   failed because:
    multimap is not a subset
```
</details>

**Comment by jamesdbloom** [comment] 2022-04-01 15:49
The schema doesn't match the field, however, it is clear the log output isn't clear enough so I've improve the error output when these types of fields don't match.  After doing that the code below shows what the problem is in the request:

The following code shows what the issue is:

```java
package org.mockserver.examples;

import com.google.common.collect.ImmutableMap;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClientBuilder;
import org.mockserver.integration.ClientAndServer;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.stream.Collectors;

import static org.mockserver.configuration.Configuration.configuration;
import static org.mockserver.integration.ClientAndServer.startClientAndServer;
import static org.mockserver.mock.OpenAPIExpectation.openAPIExpectation;

public class _test {

    public static void main(String[] args) throws Exception {
        ClientAndServer mockServer = startClientAndServer(
            configuration()
                .logLevel("DEBUG"),
            1080
        );
        mockServer
            .upsert(
                openAPIExpectation("/Users/jamesbloom/git/mockserver/mockserver/bug/mock/config/spec_master.yaml")
                    .withOperationsAndResponses(ImmutableMap.of(
                        "api.controllers.agent_controller.get_agents", "200"
                    ))
            );

//        getRequest("http://localhost:" + mockServer.getPort() + "/agents?limit=500");
        getRequest("http://localhost:" + mockServer.getPort() + "/agents?agents_list=000");
    }

    private static void getRequest(String uri) throws IOException {
        CloseableHttpClient httpClient = HttpClientBuilder.create().build();
        HttpGet httpGet = new HttpGet(uri);
        httpGet.setHeader("authorization", "bearer sadsfghjkgfdsafghjk");
        CloseableHttpResponse httpResponse = httpClient.execute(httpGet);

        System.out.println("statusCode: " + httpResponse.getStatusLine().getStatusCode());
        try (InputStreamReader isr = new InputStreamReader(httpResponse.getEntity().getContent()); BufferedReader br = new BufferedReader(isr);) {
            System.out.println("responseBody:\n" + br.lines().collect(Collectors.joining("\n")));
        }
    }

}
```

This outputs the following logs:

```bash
2022-04-01 16:46:40 5.13.1-SNAPSHOT INFO 1080 started on port: 1080 
2022-04-01 16:46:41 5.13.1-SNAPSHOT INFO 1080 creating expectation:

  {
    "httpRequest" : {
      "operationId" : "api.controllers.agent_controller.get_agents",
      "specUrlOrPayload" : "/Users/jamesbloom/git/mockserver/mockserver/bug/mock/config/spec_master.yaml"
    },
    "httpResponse" : {
      "statusCode" : 200,
      "headers" : {
        "content-type" : [ "application/json" ]
      },
      "body" : "{\n  \"data\" : {\n    \"affected_items\" : [ {\n      \"os\" : {\n        \"arch\" : \"x86_64\",\n        \"codename\" : \"Focal Fossa\",\n        \"major\" : \"20\",\n        \"minor\" : \"04\",\n        \"name\" : \"Ubuntu\",\n        \"platform\" : \"ubuntu\",\n        \"uname\" : \"Linux |ac7cb188d538 |5.8.0-45-generic |#51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021 |x86_64\",\n        \"version\" : \"20.04.2 LTS\"\n      },\n      \"lastKeepAlive\" : \"2021-05-26T12:40:40Z\",\n      \"id\" : \"001\",\n      \"dateAdd\" : \"2021-05-26T12:40:08Z\",\n      \"configSum\" : \"ab73af41699f13fdd81903b5f23d8d00\",\n      \"manager\" : \"wazuh-worker2\",\n      \"group\" : [ \"default\" ],\n      \"registerIP\" : \"Any\",\n      \"ip\" : \"172.25.0.6\",\n      \"name\" : \"ac7cb188d538\",\n      \"status\" : \"active\",\n      \"mergedSum\" : \"9a016508cea1e997ab8569f5cfab30f5\",\n      \"version\" : \"Wazuh v4.3.0\",\n      \"node_name\" : \"worker2\",\n      \"group_config_status\" : \"synced\"\n    }, {\n      \"os\" : {\n        \"arch\" : \"x86_64\",\n        \"codename\" : \"Focal Fossa\",\n        \"major\" : \"20\",\n        \"minor\" : \"04\",\n        \"name\" : \"Ubuntu\",\n        \"platform\" : \"ubuntu\",\n        \"uname\" : \"Linux |ac7cb188d538 |5.8.0-45-generic |#51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021 |x86_64\",\n        \"version\" : \"20.04.2 LTS\"\n      },\n      \"lastKeepAlive\" : \"2021-05-26T12:40:40Z\",\n      \"id\" : \"002\",\n      \"dateAdd\" : \"2021-05-26T12:40:10Z\",\n      \"configSum\" : \"ab73af41699f13fdd81903b5f23d8d00\",\n      \"manager\" : \"wazuh-worker2\",\n      \"group\" : [ \"default\" ],\n      \"registerIP\" : \"Any\",\n      \"ip\" : \"172.25.0.11\",\n      \"name\" : \"91642a418627\",\n      \"status\" : \"active\",\n      \"mergedSum\" : \"9a016508cea1e997ab8569f5cfab30f5\",\n      \"version\" : \"Wazuh v4.3.0\",\n      \"node_name\" : \"worker2\",\n      \"group_config_status\" : \"synced\"\n    }, {\n      \"os\" : {\n        \"arch\" : \"x86_64\",\n        \"codename\" : \"Focal Fossa\",\n        \"major\" : \"20\",\n        \"minor\" : \"04\",\n        \"name\" : \"Ubuntu\",\n        \"platform\" : \"ubuntu\",\n        \"uname\" : \"Linux |ac7cb188d538 |5.8.0-45-generic |#51~20.04.1-Ubuntu SMP Tue Feb 23 13:46:31 UTC 2021 |x86_64\",\n        \"version\" : \"20.04.2 LTS\"\n      },\n      \"lastKeepAlive\" : \"2021-05-26T12:40:40Z\",\n      \"id\" : \"003\",\n      \"dateAdd\" : \"2021-05-26T12:40:10Z\",\n      \"configSum\" : \"ab73af41699f13fdd81903b5f23d8d00\",\n      \"manager\" : \"wazuh-worker2\",\n      \"group\" : [ \"default\" ],\n      \"registerIP\" : \"Any\",\n      \"ip\" : \"172.25.0.10\",\n      \"name\" : \"a442e15bc84e\",\n      \"status\" : \"active\",\n      \"mergedSum\" : \"9a016508cea1e997ab8569f5cfab30f5\",\n      \"version\" : \"Wazuh v4.3.0\",\n      \"node_name\" : \"worker1\",\n      \"group_config_status\" : \"not synced\"\n    } ],\n    \"total_affected_items\" : 3,\n    \"total_failed_items\" : 0,\n    \"failed_items\" : [ ]\n  },\n  \"message\" : \"All selected agents information was returned\",\n  \"error\" : 0\n}"
    },
    "id" : "00000000-2abf-010e-0000-00002abf010e",
    "priority" : 0,
    "timeToLive" : {
      "unlimited" : true
    },
    "times" : {
      "unlimited" : true
    }
  }

 with id:

  00000000-2abf-010e-0000-00002abf010e
 
2022-04-01 16:46:42 5.13.1-SNAPSHOT INFO 1080 received request:

  {
    "method" : "GET",
    "path" : "/agents",
    "queryStringParameters" : {
      "agents_list" : [ "000" ]
    },
    "headers" : {
      "content-length" : [ "0" ],
      "authorization" : [ "bearer sadsfghjkgfdsafghjk" ],
      "User-Agent" : [ "Apache-HttpClient/4.5.13 (Java/1.8.0_201)" ],
      "Host" : [ "localhost:1080" ],
      "Connection" : [ "Keep-Alive" ],
      "Accept-Encoding" : [ "gzip,deflate" ]
    },
    "keepAlive" : true,
    "secure" : false,
    "remoteAddress" : "127.0.0.1"
  }
 
2022-04-01 16:46:42 5.13.1-SNAPSHOT INFO 1080 request:

  {
    "method" : "GET",
    "path" : "/agents",
    "queryStringParameters" : {
      "agents_list" : [ "000" ]
    },
    "headers" : {
      "content-length" : [ "0" ],
      "authorization" : [ "bearer sadsfghjkgfdsafghjk" ],
      "User-Agent" : [ "Apache-HttpClient/4.5.13 (Java/1.8.0_201)" ],
      "Host" : [ "localhost:1080" ],
      "Connection" : [ "Keep-Alive" ],
      "Accept-Encoding" : [ "gzip,deflate" ]
    },
    "keepAlive" : true,
    "secure" : false,
    "remoteAddress" : "127.0.0.1"
  }

 didn't match open api "...kserver/bug/mock/config/spec_master.yaml" operation "api.controllers.agent_controller.get_agents" request matcher:

  {
    "method" : "GET",
    "path" : "/agents",
    "queryStringParameters" : {
      "keyMatchStyle" : "MATCHING_KEY",
      "?wait_for_complete" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "default" : false,
            "type" : "boolean"
          }
        } ]
      },
      "?version" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "format" : "alphanumeric",
            "type" : "string"
          }
        } ]
      },
      "?status" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "items" : {
              "enum" : [ "active", "pending", "never_connected", "disconnected" ],
              "type" : "string"
            },
            "minItems" : 1,
            "type" : "array"
          }
        } ]
      },
      "?sort" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "format" : "sort",
            "type" : "string"
          }
        } ]
      },
      "?select" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "items" : {
              "format" : "names",
              "type" : "string"
            },
            "type" : "array"
          }
        } ]
      },
      "?search" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "format" : "search",
            "type" : "string"
          }
        } ]
      },
      "?registerIP" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "format" : "alphanumeric",
            "type" : "string"
          }
        } ]
      },
      "?q" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "type" : "string"
          }
        } ]
      },
      "?pretty" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "default" : false,
            "type" : "boolean"
          }
        } ]
      },
      "?os.version" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "format" : "alphanumeric",
            "type" : "string"
          }
        } ]
      },
      "?os.platform" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "format" : "alphanumeric",
            "type" : "string"
          }
        } ]
      },
      "?os.name" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "format" : "alphanumeric",
            "type" : "string"
          }
        } ]
      },
      "?older_than" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "format" : "timeframe",
            "type" : "string"
          }
        } ]
      },
      "?offset" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "default" : 0,
            "format" : "int32",
            "minimum" : 0,
            "type" : "integer"
          }
        } ]
      },
      "?node_name" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "format" : "names",
            "type" : "string"
          }
        } ]
      },
      "?name" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "format" : "alphanumeric",
            "type" : "string"
          }
        } ]
      },
      "?manager" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "format" : "alphanumeric",
            "type" : "string"
          }
        } ]
      },
      "?limit" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "default" : 500,
            "format" : "int32",
            "maximum" : 100000.0,
            "minimum" : 1,
            "type" : "integer"
          }
        } ]
      },
      "?ip" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "format" : "alphanumeric",
            "type" : "string"
          }
        } ]
      },
      "?group_config_status" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "enum" : [ "synced", "not synced" ],
            "type" : "string"
          }
        } ]
      },
      "?group" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "description" : "Group name",
            "format" : "group_names",
            "type" : "string"
          }
        } ]
      },
      "?agents_list" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "items" : {
              "description" : "Agent ID",
              "format" : "numbers",
              "minLength" : 3,
              "type" : "string"
            },
            "type" : "array"
          }
        } ]
      }
    },
    "headers" : {
      "authorization" : [ "bearer.+" ]
    }
  }

 because:

  method matched
  path matched
  body matched
  headers matched
  cookies matched
  pathParameters matched
  queryParameters didn't match: 
  
    schema match failed expect:
  
      {
        "items" : {
          "description" : "Agent ID",
          "format" : "numbers",
          "minLength" : 3,
          "type" : "string"
        },
        "type" : "array"
      }
  
     found:
  
      000
  
     errors:
  
      1 error:
       - $: integer found, array expected
  
    multimap matching key match failed for key:
  
      ?agents_list
  
    multimap match failed expected:
  
      {
        "keyMatchStyle" : "MATCHING_KEY",
        "?wait_for_complete" : {
          "parameterStyle" : "FORM_EXPLODED",
          "values" : [ {
            "schema" : {
              "default" : false,
              "type" : "boolean"
            }
          } ]
        },
        "?version" : {
          "parameterStyle" : "FORM_EXPLODED",
          "values" : [ {
            "schema" : {
              "format" : "alphanumeric",
              "type" : "string"
            }
          } ]
        },
        "?status" : {
          "parameterStyle" : "FORM_EXPLODED",
          "values" : [ {
            "schema" : {
              "items" : {
                "enum" : [ "active", "pending", "never_connected", "disconnected" ],
                "type" : "string"
              },
              "minItems" : 1,
              "type" : "array"
            }
          } ]
        },
        "?sort" : {
          "parameterStyle" : "FORM_EXPLODED",
          "values" : [ {
            "schema" : {
              "format" : "sort",
              "type" : "string"
            }
          } ]
        },
        "?select" : {
          "parameterStyle" : "FORM_EXPLODED",
          "values" : [ {
            "schema" : {
              "items" : {
                "format" : "names",
                "type" : "string"
              },
              "type" : "array"
            }
          } ]
        },
        "?search" : {
          "parameterStyle" : "FORM_EXPLODED",
          "values" : [ {
            "schema" : {
              "format" : "search",
              "type" : "string"
            }
          } ]
        },
        "?registerIP" : {
          "parameterStyle" : "FORM_EXPLODED",
          "values" : [ {
            "schema" : {
              "format" : "alphanumeric",
              "type" : "string"
            }
          } ]
        },
        "?q" : {
          "parameterStyle" : "FORM_EXPLODED",
          "values" : [ {
            "schema" : {
              "type" : "string"
            }
          } ]
        },
        "?pretty" : {
          "parameterStyle" : "FORM_EXPLODED",
          "values" : [ {
            "schema" : {
              "default" : false,
              "type" : "boolean"
            }
          } ]
        },
        "?os.version" : {
          "parameterStyle" : "FORM_EXPLODED",
          "values" : [ {
            "schema" : {
              "format" : "alphanumeric",
              "type" : "string"
            }
          } ]
        },
        "?os.platform" : {
          "parameterStyle" : "FORM_EXPLODED",
          "values" : [ {
            "schema" : {
              "format" : "alphanumeric",
              "type" : "string"
            }
          } ]
        },
        "?os.name" : {
          "parameterStyle" : "FORM_EXPLODED",
          "values" : [ {
            "schema" : {
              "format" : "alphanumeric",
              "type" : "string"
            }
          } ]
        },
        "?older_than" : {
          "parameterStyle" : "FORM_EXPLODED",
          "values" : [ {
            "schema" : {
              "format" : "timeframe",
              "type" : "string"
            }
          } ]
        },
        "?offset" : {
          "parameterStyle" : "FORM_EXPLODED",
          "values" : [ {
            "schema" : {
              "default" : 0,
              "format" : "int32",
              "minimum" : 0,
              "type" : "integer"
            }
          } ]
        },
        "?node_name" : {
          "parameterStyle" : "FORM_EXPLODED",
          "values" : [ {
            "schema" : {
              "format" : "names",
              "type" : "string"
            }
          } ]
        },
        "?name" : {
          "parameterStyle" : "FORM_EXPLODED",
          "values" : [ {
            "schema" : {
              "format" : "alphanumeric",
              "type" : "string"
            }
          } ]
        },
        "?manager" : {
          "parameterStyle" : "FORM_EXPLODED",
          "values" : [ {
            "schema" : {
              "format" : "alphanumeric",
              "type" : "string"
            }
          } ]
        },
        "?limit" : {
          "parameterStyle" : "FORM_EXPLODED",
          "values" : [ {
            "schema" : {
              "default" : 500,
              "format" : "int32",
              "maximum" : 100000.0,
              "minimum" : 1,
              "type" : "integer"
            }
          } ]
        },
        "?ip" : {
          "parameterStyle" : "FORM_EXPLODED",
          "values" : [ {
            "schema" : {
              "format" : "alphanumeric",
              "type" : "string"
            }
          } ]
        },
        "?group_config_status" : {
          "parameterStyle" : "FORM_EXPLODED",
          "values" : [ {
            "schema" : {
              "enum" : [ "synced", "not synced" ],
              "type" : "string"
            }
          } ]
        },
        "?group" : {
          "parameterStyle" : "FORM_EXPLODED",
          "values" : [ {
            "schema" : {
              "description" : "Group name",
              "format" : "group_names",
              "type" : "string"
            }
          } ]
        },
        "?agents_list" : {
          "parameterStyle" : "FORM_EXPLODED",
          "values" : [ {
            "schema" : {
              "items" : {
                "description" : "Agent ID",
                "format" : "numbers",
                "minLength" : 3,
                "type" : "string"
              },
              "type" : "array"
            }
          } ]
        }
      }
  
     found:
  
      {
        "agents_list" : [ "000" ]
      }
  
     failed because:
  
      multimap values don't match

 
2022-04-01 16:46:42 5.13.1-SNAPSHOT INFO 1080 no expectation for:

  {
    "method" : "GET",
    "path" : "/agents",
    "queryStringParameters" : {
      "agents_list" : [ "000" ]
    },
    "headers" : {
      "content-length" : [ "0" ],
      "authorization" : [ "bearer sadsfghjkgfdsafghjk" ],
      "User-Agent" : [ "Apache-HttpClient/4.5.13 (Java/1.8.0_201)" ],
      "Host" : [ "localhost:1080" ],
      "Connection" : [ "Keep-Alive" ],
      "Accept-Encoding" : [ "gzip,deflate" ]
    },
    "keepAlive" : true,
    "secure" : false,
    "remoteAddress" : "127.0.0.1"
  }

 returning response:

  {
    "statusCode" : 404,
    "reasonPhrase" : "Not Found"
  }
 
statusCode: 404
responseBody:

```

The error in the log above is:

```json

  }

 because:

  method matched
  path matched
  body matched
  headers matched
  cookies matched
  pathParameters matched
  queryParameters didn't match: 
  
    schema match failed expect:
  
      {
        "items" : {
          "description" : "Agent ID",
          "format" : "numbers",
          "minLength" : 3,
          "type" : "string"
        },
        "type" : "array"
      }
  
     found:
  
      000
  
     errors:
  
      1 error:
       - $: integer found, array expected
```

**Comment by jamesdbloom** [comment] 2022-04-01 15:50
Once I commit the improve log output for non-matching schema fields I'll close this issue.

**Closed** 2022-04-01 17:01 UTC

**Comment by mtheiss** [comment] 2022-04-29 11:10
This opened a regression, when log level is set to debug.

At RegexStringMatcher.java:52 the mockServerLogger is set to null, but it is accessed for example in RegexStringMatcher.java:123
 
```
java.lang.NullPointerException
    at org.mockserver.matchers.RegexStringMatcher.matchesByStrings (RegexStringMatcher.java:123)
    at org.mockserver.matchers.RegexStringMatcher.matchesByNottedStrings (RegexStringMatcher.java:73)
    at org.mockserver.matchers.RegexStringMatcher.matches (RegexStringMatcher.java:63)
    at org.mockserver.matchers.RegexStringMatcher.matches (RegexStringMatcher.java:52)
    at org.mockserver.collections.SubSetMatcher.matchesIndexes (SubSetMatcher.java:41)
    at org.mockserver.collections.SubSetMatcher.containsSubset (SubSetMatcher.java:18)
    at org.mockserver.collections.NottableStringMultiMap.containsAll (NottableStringMultiMap.java:52)
    at org.mockserver.matchers.MultiValueMapMatcher.matches (MultiValueMapMatcher.java:50)
    at org.mockserver.matchers.MultiValueMapMatcher.matches (MultiValueMapMatcher.java:15)
    at org.mockserver.matchers.HttpRequestPropertiesMatcher.matches (HttpRequestPropertiesMatcher.java:472)
    at org.mockserver.matchers.HttpRequestPropertiesMatcher.matches (HttpRequestPropertiesMatcher.java:289)
    at org.mockserver.matchers.HttpRequestPropertiesMatcher.matches (HttpRequestPropertiesMatcher.java:202)
    at org.mockserver.log.model.LogEntry.matches (LogEntry.java:202)
    at org.mockserver.log.MockServerEventLog.lambda$null$28 (MockServerEventLog.java:434)
    at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:176)
    at java.util.concurrent.ConcurrentLinkedDeque$CLDSpliterator.forEachRemaining (ConcurrentLinkedDeque.java:1483)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:484)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:474)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential (ReduceOps.java:913)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect (ReferencePipeline.java:578)
    at org.mockserver.log.MockServerEventLog.lambda$retrieveRequests$14 (MockServerEventLog.java:289)
    at org.mockserver.log.MockServerEventLog.lambda$retrieveLogEntries$29 (MockServerEventLog.java:432)
    at org.mockserver.log.MockServerEventLog.lambda$startRingBuffer$7 (MockServerEventLog.java:144)
    at com.lmax.disruptor.BatchEventProcessor.processEvents (BatchEventProcessor.java:168)
    at com.lmax.disruptor.BatchEventProcessor.run (BatchEventProcessor.java:125)
    at java.lang.Thread.run (Thread.java:829)
```

**Comment by AlexRuiz7** [comment] 2022-05-19 15:20
Hello again

I still can't use arrays as query parameters on a request using an OpenAPI spec.

To simplify the scenario and conclude whether there is an error with our OpenAPI schema or with the MockServer itself, I did some tests with the well known Pets Store schema. This schema defines the endpoint /pet/findByTags, which accepts the ?tags query parameter. This endpoint can be tried online on https://petstore3.swagger.io/ and can look like this:

https://petstore3.swagger.io/api/v3/pet/findByTags?tags=tag1&tags=tag2&tags=tag3

```yml
  /pet/findByTags:
    get:
      tags:
        - pet
      summary: Finds Pets by tags
      description: >-
        Multiple tags can be provided with comma separated strings. Use tag1,
        tag2, tag3 for testing.
      operationId: findPetsByTags
      parameters:
        - name: tags
          in: query
          description: Tags to filter by
          required: false
          explode: false
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        '400':
          description: Invalid tag value
```


However, if I import this schema and operation and try it out, the MockServer returns a 404 response as it decided that the request does not match any expectation, when imo it should.

Here's the import:
```json
{
    "specUrlOrPayload": "https://raw.githubusercontent.com/swagger-api/swagger-petstore/master/src/main/resources/openapi.yaml",
    "operationsAndResponses": {
        "findPetsByTags": "200"
    }
}
```

Here's the request (as logged by the MockServer):
```json
{
  "method": "GET",
  "path": "/pet/findByTags",
  "queryStringParameters": {
    "tags": [
      "tag1",
      "tag2",
      "tag3"
    ]
  },
}
```

Here's the expectation (as logged by the MockServer):
```json
{
  "method": "GET",
  "path": "/pet/findByTags",
  "queryStringParameters": {
    "keyMatchStyle": "MATCHING_KEY",
    "?tags": {
      "parameterStyle": "FORM_EXPLODED",
      "values": [
        {
          "schema": {
            "items": {
              "type": "string"
            },
            "type": "array"
          }
        }
      ]
    }
  }
}
```

And here's the cause:
```java
method matched
path matched
body matched
headers matched
cookies matched
pathParameters matched
queryParameters didn't match: 
  schema match failed expect:
    {
      "items" : {
        "type" : "string"
      },
      "type" : "array"
    }
   found:
    tag1
   errors:
    JsonParseException - Unrecognized token 'tag1': was expecting (JSON String, Number (or 'NaN'/'INF'/'+INF'), Array, Object or token 'null', 'true' or 'false')
     at [Source: (String)"tag1"; line: 1, column: 5]
  multimap matching key match failed for key:
    ?tags
  multimap match failed expected:
    {
      "keyMatchStyle" : "MATCHING_KEY",
      "?tags" : {
        "parameterStyle" : "FORM_EXPLODED",
        "values" : [ {
          "schema" : {
            "items" : {
              "type" : "string"
            },
            "type" : "array"
          }
        } ]
      }
    }
   found:
    {
      "tags" : [ "tag1", "tag2", "tag3" ]
    }
   failed because:
    multimap values don't match
```
