### ISSUE TITLE
Should be given Complete Example of HTTPS request

### ISSUE THREAD

**Issue by irshad97feb** [mock-server/mockserver#1107] opened 2021-12-09 05:36 UTC
**Describe the feature request**
Should have complete example of HTTPs connection using docker and helm chart

**What you are trying to do**
Trying to create HTTPs connection but not able to to.

**The solution you'd like**
Can be given a very good example with HTTPs connection using both docker and helm chart based configurations.

**Comment by astrieanna** [comment] 2022-02-03 19:34
I think my current problem would also be solved by this documentation. Specifically, I'm using `mkcert` to generate a locally trusted rootCA, and I'd like to either give mock-server the rootCA or a cert generated with `mkcert`, but I'm getting all kinds of java SSL errors that the current documentation doesn't help with.

**Comment by jamesdbloom** [comment] 2022-03-18 21:31
Duplicate of https://github.com/mock-server/mockserver/issues/1107 so closing this issue

**Closed by jamesdbloom** 2022-03-18 21:31 UTC
Labels: enhancement, documentation, next
