### ISSUE TITLE
Post Request Fail from HttpClient

### ISSUE THREAD

**Issue by ray-morehead** [mock-server/mockserver#746] opened 2020-03-19 13:49 UTC
**Describe the issue**
Body is not getting filled on post requests from org.apache.http.client.methods.HttpPost;

**MockServer version**
The version you are using (i.e. 5.9.0)

**To Reproduce**
Seems like the HttpPost method for filling a body (with an InputStream) isn't getting picked up by the mock server.

Here's the pertinent logs:
------------------------------------
2020-03-19 13:45:35 - request:

	{
	  "method" : "POST",
	  "path" : "/search/csr",
	  "headers" : {
	    "Accept" : [ "application/json" ],
	    "Content-type" : [ "application/json; UTF-8" ],
	    "Authorization" : [ "TestJWT" ],
	    "Content-Length" : [ "136" ],
	    "Host" : [ "localhost:33179" ],
	    "Connection" : [ "Keep-Alive" ],
	    "User-Agent" : [ "Apache-HttpClient/4.5.5 (Java/1.8.0_191)" ],
	    "Accept-Encoding" : [ "gzip,deflate" ]
	  }
	}

 didn't match expectation:

	{
	  "id" : "8a410f0e-756e-4fe7-bb77-4e8ee82f932d",
	  "httpRequest" : {
	    "method" : "POST",
	    "path" : "/search/csr",
	    "headers" : {
	      "Authorization" : [ "TestJWT" ]
	    },
	    "body" : "{\"wkt\":\"wkt\",\"cellsHigh\":5,\"cellsWide\":5,\"thumbnails\":true,\"sortType\":\"MD5\",\"sortSubtype\":\"DESCENDING\",\"clipToAOI\":true,\"categories\":[]}"
	  },
	  "times" : {
	    "unlimited" : true
	  },
	  "timeToLive" : {
	    "unlimited" : true
	  },
	  "httpResponse" : {
	    "body" : "{\"numFound\":0,\"searchGuid\":\"someGuid\"}"
	  }
	}

 because:

	method matched,
	path matched,
	body didn't match

But I did create the body -- the mock seems to ignore  it:
-----------------------------------

 String body = gson.toJson(csrRequest, CSRRequest.class);

            StringEntity stringEntity = new StringEntity(body);
            httpPost.setEntity(stringEntity);

            httpPost.setHeader("Accept", "application/json");
            httpPost.setHeader("Content-type", "application/json; UTF-8");
            httpPost.setHeader("Authorization", token);

            HttpEntity e = httpPost.getEntity();
            System.out.println(new BufferedReader(new InputStreamReader(e.getContent())).readLine());
->
{"wkt":"wkt","cellsHigh":5,"cellsWide":5,"thumbnails":true,"sortType":"MD5","sortSubtype":"DESCENDING","clipToAOI":true,"categories":[]}

**Comment by jamesdbloom** [comment] 2020-06-02 05:45
This issue was caused by an invalid `Content-Type` header, in particular the parameters sections is invalid (see https://www.w3.org/Protocols/rfc1341/4_Content-Type.html):

```java
ClientAndServer clientAndServer = startClientAndServer(1080);
clientAndServer.when(request().withBody("some_random_request_body")).respond(response().withBody("some_random_response_body"));

HttpClient httpClient = HttpClients.createDefault();
HttpPost httpPost = new HttpPost(
    new URIBuilder()
        .setScheme("http")
        .setHost("127.0.0.1")
        .setPort(clientAndServer.getLocalPort())
        .build()
);

httpPost.setEntity(new StringEntity("some_random_request_body"));

httpPost.setHeader("Accept", "application/json");
httpPost.setHeader("Content-type", "application/json; UTF-8");
//        the line above should be: httpPost.setHeader("Content-type", "application/json;charset=utf-8");
httpPost.setHeader("Authorization", "TestJWT");

HttpResponse response = httpClient.execute(httpPost);
HttpEntity entity = response.getEntity();
System.out.println(new BufferedReader(new InputStreamReader(entity.getContent())).readLine());
```

I have however improved the error handling in MockServer and made MockServer ignore incorrect values, so now for the following is the output for the code above:

```bash
2020-06-02 06:41:54  org.mockserver.log.MockServerEventLog  INFO  started on port: 1080 
2020-06-02 06:41:55  org.mockserver.log.MockServerEventLog  INFO  creating expectation:

  {
    "id" : "30b85744-5810-434c-9025-b34e5b5c86b4",
    "priority" : 0,
    "httpRequest" : {
      "body" : "some_random_request_body"
    },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpResponse" : {
      "body" : "some_random_response_body"
    }
  }
 
2020-06-02 06:41:55  org.mockserver.serialization.ObjectMapperFactory  WARNING  invalid parameters format "utf-8", expected

  Content-Type := type "/" subtype *[";" parameter]
  parameter := attribute "=" value

 see:

  https://www.w3.org/Protocols/rfc1341/4_Content-Type.html
 
java.lang.IllegalArgumentException: Chunk [utf-8] is not a valid entry
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:217)
	at com.google.common.base.Splitter$MapSplitter.split(Splitter.java:526)
	at org.mockserver.model.MediaType.parse(MediaType.java:103)
	at org.mockserver.codec.BodyDecoderEncoder.bytesToBody(BodyDecoderEncoder.java:125)
	at org.mockserver.codec.BodyDecoderEncoder.byteBufToBody(BodyDecoderEncoder.java:98)
	at org.mockserver.mappers.FullHttpRequestToMockServerRequest.setBody(FullHttpRequestToMockServerRequest.java:118)
	at org.mockserver.mappers.FullHttpRequestToMockServerRequest.mapFullHttpRequestToMockServerRequest(FullHttpRequestToMockServerRequest.java:49)
	at org.mockserver.codec.NettyHttpToMockServerRequestDecoder.decode(NettyHttpToMockServerRequestDecoder.java:24)
	at org.mockserver.codec.NettyHttpToMockServerRequestDecoder.decode(NettyHttpToMockServerRequestDecoder.java:14)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.mockserver.dashboard.DashboardWebSocketServerHandler.channelRead(DashboardWebSocketServerHandler.java:130)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.mockserver.closurecallback.websocketregistry.CallbackWebSocketServerHandler.channelRead(CallbackWebSocketServerHandler.java:56)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.mockserver.netty.unification.PortUnificationHandler.switchToHttp(PortUnificationHandler.java:231)
	at org.mockserver.netty.unification.PortUnificationHandler.decode(PortUnificationHandler.java:128)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)

2020-06-02 06:41:55  org.mockserver.log.MockServerEventLog  INFO  received request:

  {
    "method" : "POST",
    "path" : "/",
    "headers" : {
      "Accept" : [ "application/json" ],
      "Content-type" : [ "application/json; UTF-8" ],
      "Authorization" : [ "TestJWT" ],
      "Content-Length" : [ "24" ],
      "Host" : [ "127.0.0.1:1080" ],
      "Connection" : [ "Keep-Alive" ],
      "User-Agent" : [ "Apache-HttpClient/4.5.10 (Java/1.8.0_201)" ],
      "Accept-Encoding" : [ "gzip,deflate" ]
    },
    "keepAlive" : true,
    "secure" : false,
    "body" : "some_random_request_body"
  }
 
2020-06-02 06:41:55  org.mockserver.log.MockServerEventLog  INFO  request:

  {
    "method" : "POST",
    "path" : "/",
    "headers" : {
      "Accept" : [ "application/json" ],
      "Content-type" : [ "application/json; UTF-8" ],
      "Authorization" : [ "TestJWT" ],
      "Content-Length" : [ "24" ],
      "Host" : [ "127.0.0.1:1080" ],
      "Connection" : [ "Keep-Alive" ],
      "User-Agent" : [ "Apache-HttpClient/4.5.10 (Java/1.8.0_201)" ],
      "Accept-Encoding" : [ "gzip,deflate" ]
    },
    "keepAlive" : true,
    "secure" : false,
    "body" : "some_random_request_body"
  }

 matched expectation:

  {
    "id" : "30b85744-5810-434c-9025-b34e5b5c86b4",
    "priority" : 0,
    "httpRequest" : {
      "body" : "some_random_request_body"
    },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpResponse" : {
      "body" : "some_random_response_body"
    }
  }
 
2020-06-02 06:41:55  org.mockserver.log.MockServerEventLog  INFO  returning response:

  {
    "body" : "some_random_response_body"
  }

 for request:

  {
    "method" : "POST",
    "path" : "/",
    "headers" : {
      "Accept" : [ "application/json" ],
      "Content-type" : [ "application/json; UTF-8" ],
      "Authorization" : [ "TestJWT" ],
      "Content-Length" : [ "24" ],
      "Host" : [ "127.0.0.1:1080" ],
      "Connection" : [ "Keep-Alive" ],
      "User-Agent" : [ "Apache-HttpClient/4.5.10 (Java/1.8.0_201)" ],
      "Accept-Encoding" : [ "gzip,deflate" ]
    },
    "keepAlive" : true,
    "secure" : false,
    "body" : "some_random_request_body"
  }

 for action:

  {
    "body" : "some_random_response_body"
  }
 
some_random_response_body
```

**Comment by jamesdbloom** [comment] 2020-06-02 06:38
closing ticket as improved parsing of invalid content-type header parameters by handling error gracefully and outputting a clear error message

**Comment by jamesdbloom** [comment] 2020-06-02 06:38
this will be available in the SNAPSHOT version in the next 20 mins

**Closed by jamesdbloom** 2020-06-02 06:38 UTC
