### ISSUE TITLE
Matching binary request body (e.g. protobuf)

### ISSUE THREAD

**Issue by punya-asapp** [mock-server/mockserver#682] opened 2019-10-23 16:59 UTC
We use an RPC system similar to [Twirp](https://twitchtv.github.io/twirp/), which uses HTTP requests/responses with bodies serialized using [Protocol bufffers](https://developers.google.com/protocol-buffers). We'd like to use mockserver to serve, match and verify such bodies.

It seems impractical for mockserver's built-in matchers to support every possible data format (Protobuf, Thrift, Avro, ...). Would it make sense to have a plugin API so that people could add support for the flavors they need?

**Comment by jamesdbloom** [comment] 2019-10-26 21:06
MockServer supports both binary body matchers and binary response bodies so it would be possible to perform any exact binary body match / response.  Would this meet your needs or would you think a more flexible matcher be useful?

**Comment by jamesdbloom** [comment] 2019-11-16 13:15
This is a duplicate of #265 so I'm closing the other older ticket.

**Comment by jamesdbloom** [comment] 2019-12-01 07:24
MockServer supports both binary body matchers and binary response bodies so it would be possible to perform any exact binary body match / response. Would this meet your needs or would you think a more flexible matcher be useful?

@punya-asapp is there any update on this?

**Comment by punya-asapp** [comment] 2019-12-05 17:58
If a server returns a JSON message like

```json
{
  "data": 42,
  "ts": "2019-12-05T17:55:25.479Z"
}
```

where `timestamp` is meaningless for test purposes, it's possible to write a matcher that only considers the `data` field.

If the same sort of message is returned in a binary format (such as protobuf), it's impossible to do an *exact* match, and we must resort to saving the full body and manually extracting/verifying the relevant fields. That's the gap I was highlighting in my request.

**Comment by jamesdbloom** [comment] 2019-12-05 20:10
@punya-asapp I understand you feature you have asked for now.  

Implementing such support would be incredibly complex because there is no standard format for binary bodies.  Protobuf isn't a standard format because it requires knowledge of the proto file to make sense of the binary format.  It may be possible though if the proto file was submitted as part of the expectation.  

In addition, it may also be possible to support custom body matchers or request matchers by providing a class or potentially even a closure.  That would allow any custom matching requirements to be implemented.  

I'll add an item to the backlog for that, and close this ticket as this will now be tracked on the backlog: https://trello.com/c/9SYkd4gb/64-custom-matchers

**Closed by jamesdbloom** 2019-12-05 20:10 UTC
Labels: need_more_information, question

**Comment by jamesdbloom** [comment] 2019-12-05 20:12
Something can likely be implemented to support either protobuf or customer matches (or both) in the next couple of months.  I'll start with custom matchers for bodies because then you're be in a position to support protobuf or other binary body formats.

**Comment by rebbuh** [comment] 2020-08-06 15:47
Hi James,
any updates on your plans to implement a custom matcher?
We receive a base64-encoded SOAP request and would like to match some parts of the base64-**decoded** body.

**Comment by alitoufighi** [comment] 2021-11-06 12:32
Guys, any updates on this?
@jamesdbloom

**Comment by tristancaron** [comment] 2024-09-21 02:53
In case some people are looking for a way to achieve this. Here is an inspiration using Kotlin, Mockk and Wire. 

Use somewhere in the code
```kt
mockkConstructor(BinaryMatcher::class)
```

Then

```kt
@OptIn(ExperimentalUuidApi::class)
fun HttpRequest.withProtoFilter(filter: MyProtoClass.() -> Boolean): HttpRequest {
    val byteArrayRef = Uuid.random().toByteArray()

    every {
        constructedWith<BinaryMatcher>(
            OfTypeMatcher<MockServerLogger>(MockServerLogger::class),
            EqMatcher(byteArrayRef)
        ).matches(any<MatchDifference>(), any<ByteArray>())
    } answers {
        val protoClass = it.invocation.args[1] as ByteArray
        val protoRequest = MyProtoClass.ADAPTER.decode(protoClass)
        protoClass.filter()
    }

    return withBody(byteArrayRef)
}
```

And used
```kt
serverClient
    .`when`(request().withProtoFilter {
        extra.isImportant
    })
    .respond() // ...
```
