### ISSUE TITLE
Memory leak with Java class callbacks

### ISSUE THREAD

**Issue by MahatmaFatalError** [mock-server/mockserver#801] opened 2020-06-18 08:45 UTC
**Describe the issue**
It seems the heap memory gets eaten up over time when serving lots of mock requests of a `ExpectationResponseCallback`
https://www.mock-server.com/mock_server/creating_expectations.html#button_response_class_callback 

**What you are trying to do**
Serve dynamic mock responses

**MockServer version**
5.10.0

**To Reproduce**
Given this dummy handler
```
package org.acme.mockserver.handler;

import org.mockserver.mock.action.ExpectationResponseCallback;
import org.mockserver.model.HttpRequest;
import org.mockserver.model.HttpResponse;

public class SimpleHandler implements ExpectationResponseCallback {
	@Override
	public HttpResponse handle(final HttpRequest httpRequest) {
		return new HttpResponse().withHeader("Content-Type", "application/json").withStatusCode(200);
	}
}
```
in a local maven project org.acme.mockserver:mock-handler:0.0.1 I started the mockserver in a different project via mvn plugin
```
<plugin>
	<groupId>org.mock-server</groupId>
	<artifactId>mockserver-maven-plugin</artifactId>
	<version>5.10.0</version>
	<configuration>
		<serverPort>8080</serverPort>
		<logLevel>ERROR</logLevel>
		<disableSystemOut>true</disableSystemOut>
	</configuration>
	<dependencies>
		<dependency>
			<groupId>org.acme.mockserver</groupId>
			<artifactId>mock-handler</artifactId>
			<version>0.0.1</version>
		</dependency>
	</dependencies>
</plugin>
```
via `❯ mvn mockserver:run -Drun.jvmArguments="-Xms512m -Xmx1024m"`

Then I mapped the the handler to a URL via
PUT http://localhost:8080/mockserver/expectation
```
[{
	"id": "test",
    "httpRequest": {
        "method": "GET",
        "path": "/test"
    },
    "httpResponseClassCallback" : {
        "callbackClass" : "org.acme.mockserver.handler.SimpleHandler"
    }
}]
```

Then I monitored the java process with VisualVM.

Then I generated some load with Apache Bench via `ab -n 20000 -c 100 "http://localhost:8080/test"`.
I paused and repeaded it 4 times.
Results:
```
Requests per second:    395.54 [#/sec] (mean)
Time per request:       252.817 [ms] (mean)
```
but notice that sometimes ab struggles with more than 16k requests
```
Benchmarking localhost (be patient)
Completed 2000 requests
Completed 4000 requests
Completed 6000 requests
Completed 8000 requests
Completed 10000 requests
Completed 12000 requests
Completed 14000 requests
Completed 16000 requests
apr_pollset_poll: The timeout specified has expired (70007)
Total of 16468 requests completed
```

**VisualVM** shows the following increase in heap memory:
<img width="1130" alt="Bildschirmfoto 2020-06-18 um 10 35 01" src="https://user-images.githubusercontent.com/776825/84997968-80396800-b14f-11ea-8eaa-8ff58b97eb35.png">

Notice that with each iteration the GC falls back on an higher niveau. So eventually, If I further iterate I will reach the memory limits.

My assumption is that the SimpleHandler objects that are created with each requests are not deleted correctly by the GC.
I hope there is no error in the SimpleHandler dummy implementation.

**Expected behaviour**
GC cleans up and after the load test the heap usage falls back to a lower niveau, like it is the case for static expectations:
![static](https://user-images.githubusercontent.com/776825/84998764-8c71f500-b150-11ea-870d-015b59d3c0e9.png)

**MockServer Log**
Leg level set to ERROR due performance reasons.

**Comment by jamesdbloom** [comment] 2020-06-19 11:37
Thanks, I'll look into this

**Comment by jamesdbloom** [comment] 2020-07-04 06:37
I don't believe there is a memory leak with class callbacks having tested your exact scenario.

With version 5.10.0 the upper bound on the event log was too high and received requests are always recorded (so that verification always works).  This means that memory appears to creep up for a while but it does eventually stabilise as the event log reaches is maximum size and starts overwriting the oldest events.

In the current SNAPSHOT which will be released shortly the event log upper bound is a factor of available heap memory and so auto adjusts ensuring JVMs with small memory size limits are supported and too reduce massive large infrequent GCs that impact the max and p99 too much.

I have reproduced your tests successfully without any errors up to 200,000 requests twice (i.e. 400,000 total), which is 20x the number in your test.  

This did not show any memory problems as follows:

$ ab -n 200000 -c 100 "http://localhost:8080/test"
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 20000 requests
Completed 40000 requests
Completed 60000 requests
Completed 80000 requests
Completed 100000 requests
Completed 120000 requests
Completed 140000 requests
Completed 160000 requests
Completed 180000 requests
Completed 200000 requests
Finished 200000 requests


Server Software:        
Server Hostname:        localhost
Server Port:            8080

Document Path:          /test
Document Length:        0 bytes

Concurrency Level:      100
Time taken for tests:   598.596 seconds
Complete requests:      200000
Failed requests:        0
Total transferred:      17800000 bytes
HTML transferred:       0 bytes
Requests per second:    334.12 [#/sec] (mean)
Time per request:       299.298 [ms] (mean)
Time per request:       2.993 [ms] (mean, across all concurrent requests)
Transfer rate:          29.04 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        1  159 776.0     67   16340
Processing:     0  139 342.3     84    8918
Waiting:        0   97 286.6     55    8777
Total:          1  297 850.6    157   16342

Percentage of the requests served within a certain time (ms)
  50%    157
  66%    190
  75%    216
  80%    237
  90%    342
  95%    760
  98%   1844
  99%   3104
 100%  16342 (longest request)
$ ab -n 200000 -c 100 "http://localhost:8080/test"
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 20000 requests
Completed 40000 requests
Completed 60000 requests
Completed 80000 requests
Completed 100000 requests
Completed 120000 requests
Completed 140000 requests
Completed 160000 requests
Completed 180000 requests
Completed 200000 requests
Finished 200000 requests


Server Software:        
Server Hostname:        localhost
Server Port:            8080

Document Path:          /test
Document Length:        0 bytes

Concurrency Level:      100
Time taken for tests:   603.684 seconds
Complete requests:      200000
Failed requests:        0
Total transferred:      17800000 bytes
HTML transferred:       0 bytes
Requests per second:    331.30 [#/sec] (mean)
Time per request:       301.842 [ms] (mean)
Time per request:       3.018 [ms] (mean, across all concurrent requests)
Transfer rate:          28.79 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0  162 1019.5     71   23917
Processing:     0  138 336.7     89   10890
Waiting:        0   99 283.9     60   10867
Total:          1  300 1085.2    166   23919

Percentage of the requests served within a certain time (ms)
  50%    166
  66%    216
  75%    250
  80%    275
  90%    350
  95%    603
  98%   1147
  99%   2123
 100%  23919 (longest request)

![Screenshot 2020-07-04 at 07 35 58](https://user-images.githubusercontent.com/733179/86506627-1369d300-bdc9-11ea-8485-2fe13a1a631f.png)

Can you please confirm there isn't an issue on your OS with resources. For example trying rebooting your machine because I've seen ab tests causes issues on OSes when run repeatedly.  A reboot returns things back to normal.

**Comment by MahatmaFatalError** [comment] 2020-07-07 20:06
Thanks for the detailed response. I will try it again and check the latest SNAPSHOT release.

**Comment by jamesdbloom** [comment] 2020-07-16 19:31
This version is now release so please check with the latest released version 5.11.0.

**Comment by MahatmaFatalError** [comment] 2020-07-31 07:46
Sorry, hadn't the chance to continue testing with 5.11.0 since I have issues getting this version up and running in our environment.

**Comment by nitinkasat** [comment] 2020-07-31 13:58
@jamesdbloom 

We are also using callbacks and we are getting out of memory error after server started and ran for some time. After setting netty leak detection level to advanced following is what gets printed in logs. I see RelayConnectHandler a class in mock-server source code.. Am I missing any configuration or is this an issue to be looked into? I am using 5.11.1 - latest version of server with 3 GB memory allocated to pod 

ERROR 2020-07-31 13:42:15.758  ResourceLeakDetector -LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.

 my-stub-service #2:
 my-stub-service 	Hint: 'RelayConnectHandler$1#0' will handle the message from this point.
 my-stub-service 	io.netty.channel.DefaultChannelPipeline.touch(DefaultChannelPipeline.java:116)
 my-stub-service 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
 my-stub-service 	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
 my-stub-service 	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
 my-stub-service 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
 my-stub-service 	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365

**Comment by jamesdbloom** [comment] 2020-08-06 07:27
@nitinkasat can you please provide a reproducer as I reproduced the original failure that opened this issue to 20x without any detected memory leak.  As I understand the Netty leak detection is for pooled buffers.  MockServer doesn't explicitly use any pooled buffers to avoid a know issue with GC and reference counting in Netty:

> However, reference counting isn't a holy grail. If the JVM garbage-collects the pooled buffer before its underlying memory region is returned to the pool, the leaks will eventually exhaust the pool.

from: https://netty.io/wiki/using-as-a-generic-library.html

I have however checked the code again and removed a single unpooled byte buffer creation that potentially could have been causing the original Netty pooled byte buffer to not be released.

**Comment by nitinkasat** [comment] 2020-08-07 08:45
Thanks @jamesdbloom . I will try with newer version and will share reproducer test next time if I face this issue.

**Comment by jamesdbloom** [comment] 2022-01-17 13:16
Closing due to lack of information / activity

**Closed by jamesdbloom** 2022-01-17 13:16 UTC
Labels: need_more_information, unable_to_reproduce
