### ISSUE TITLE
Delay time is doubled

### ISSUE THREAD

**Issue by Alterant-zz** [mock-server/mockserver#754] opened 2020-03-30 15:39 UTC
**Describe the issue**
The delay set in response expectations doubled when expectation is matched.
Tried with  SECONDS and MILLISECONDS and different values.

**What you are trying to do**
I am trying to simulate the delay of the response.

**MockServer version**
5.9.0

**To Reproduce**
Steps to reproduce the issue:

1. How you are running MockServer - docker
2. Code you used to create expectations
```
{
    "httpRequest": {
        "method": "POST",
        "path": "/extserver",
        "body": {
            "type": "XPATH",
            "xpath": "/Envelope/Body/UpdateClientProducts/data/Key"
       }
    },
    "httpResponse": {
        "statusCode": 200,
        "headers": [
            {
                "name": "Content-Type",
                "values": [
                    "text/xml;charset=utf-8"
                ]
            }
        ],
        "body": "<soap:Envelope>some xml here</soap:Envelope>",
        "delay": {
            "timeUnit": "SECONDS",
            "value": 5
        }
    }
}
```

3. What error you saw
That is what I see in the Logs (mockserver/retrieve?type=logs):
**15:10:59** - request:
...
 matched expectation:
```
	{
	  "id" : "0532b9c1-70b9-4812-a7bd-23b05526e144",
	  "httpRequest" : {
	    "method" : "POST",
	    "path" : "/extserver",
	    "body" : {
	      "type" : "XPATH",
	      "xpath" : "/Envelope/Body/UpdateClientProducts/data/Key"
	    }
	  },
	  "times" : {
	    "unlimited" : true
	  },
	  "timeToLive" : {
	    "unlimited" : true
	  },
	  "httpResponse" : {
	    "statusCode" : 200,
	    "headers" : {
	      "Content-Type" : [ "text/xml;charset=utf-8" ]
	    },
	    "body" : "<soap:Envelope>some xml here</soap:Envelope>",
	    "delay" : {
	      "timeUnit" : "SECONDS",
	      "value" : 5
	    }
	  }
	}
```
**15:11:09** - returning response:
...

**Expected behaviour**
I expect the delay to be 5 seconds instead of 10.

**MockServer Log**
Log output, as INFO level (or lower)
Do not have at the moment.

**Comment by jamesdbloom** [comment] 2020-03-30 19:01
This is a duplicate of #721 and has been fixed in version 5.10.0

**Closed by jamesdbloom** 2020-03-30 19:01 UTC

**Comment by Alterant-zz** [comment] 2020-03-31 06:24
Great! And thanks for such a wonderful product!
