### ISSUE TITLE
Docker image 5.15.0 points to 5.14.0

### ISSUE THREAD

**Issue by JakubJablonski2-TomTom** [mock-server/mockserver#1632] opened 2023-01-12 07:10 UTC
**Describe the issue**
Description of the issue

**What you are trying to do**
Server started with docker image 5.15.0 reports itself as 5.14.0.
Server started with latest docker image reports itself as 5.15.0.

**MockServer version**
5.15.0

**To Reproduce**

```
> docker run mockserver/mockserver:5.15.0
2023-01-12 07:01:39 5.14.0 INFO using environment variables:

  [
  	SERVER_PORT=1080
  ]

 and system properties:

  [
  	mockserver.propertyFile=/config/mockserver.properties
  ]

 and command line options:

  [
  	
  ]
 
2023-01-12 07:01:39 5.14.0 INFO logger level is INFO, change using:
 - 'ConfigurationProperties.logLevel(String level)' in Java code,
 - '-logLevel' command line argument,
 - 'mockserver.logLevel' JVM system property or,
 - 'mockserver.logLevel' property value in 'mockserver.properties' 
2023-01-12 07:01:39 5.14.0 INFO 1080 started on port: 1080 

```

**Expected behaviour**
Server should report itself as 5.15.0

**MockServer Log**

**Comment by jamesdbloom** [comment] 2023-01-12 09:29
This is now fixed.

This is caused by a race condition that is hard to solve in an automated way.  The docker release pipeline pulls the latest version from maven central but there is a delay when that version is available on maven central so the first time the pipeline runs it always pulls the wrong version.

I've re-run the pipeline which fixes this, however thats not ideal.

For now I'll add a manual step to the release process to re-run this pipeline once the version is available.  Sadly the sonatype release process isn't fully automatable AFAIK as it requires a manual approval step in the nexus UI so an additional manual step is not too bad for now.

**Closed by jamesdbloom** 2023-01-12 09:29 UTC
