### ISSUE TITLE
Add native support for Apple M1 in Docker Images

### ISSUE THREAD

**Issue by ezienecker** [mock-server/mockserver#1428] opened 2022-08-06 11:34 UTC
**Describe the feature request**
It would be very helpful if Mockserver could push Docker images that support the arm64 architecture.

**What you are trying to do**
I am not familiar with the release process. I have not found any automatism for it in the project. Otherwise I would have already provided a pull request. But please see the next section, there is the solution described.

**The solution you'd like**
It would be nice if the current docker build command could swap with the following one:

`docker buildx build --platform=linux/arm64,linux/amd64 --no-cache --tag mockserver/mockserver:mockserver-5.13.2 --push ./docker && docker buildx build --platform=linux/arm64,linux/amd64 --no-cache --tag mockserver/mockserver:5.13.2 --push ./docker`

I have already executed and tested this on several projects. Some references: https://hub.docker.com/u/ezienecker

**Describe alternatives you've considered**
There is no alternative.

**Comment by dennisameling** [comment] 2022-08-16 17:10
Duplicate of https://github.com/mock-server/mockserver/issues/819#issuecomment-1023431683 - agree that this would be great to have!

**Closed** 2022-08-21 05:58 UTC
Labels: enhancement

**Comment by jamesdbloom** [comment] 2022-08-21 06:58
@dennisameling Great thanks for your help on this!!  This workflow is now added, I've also made it slightly more testable by allowing manual runs and I've tested by pushing a tag and it looks good, but I haven't run the actually image because I can't do that.  So I'm going to assume it is good and when I do a release early next week then if would be great if you could test it so that I can resolve any issues.

**Comment by ezienecker** [comment] 2022-08-22 09:21
@jamesdbloom I thank you for the release! I Tested it and it worked like a charm. please see the following outputs:

Image before arm support:

```
➜ docker run mockserver/mockserver:5.13.2
Unable to find image 'mockserver/mockserver:5.13.2' locally
5.13.2: Pulling from mockserver/mockserver
2df365faf0e3: Already exists
676ef4227e00: Already exists
a1f1879bb7de: Already exists
da5ae4bf14ed: Already exists
1305581ae00e: Already exists
1914ec2b125f: Already exists
82de9e0b8316: Pull complete
Digest: sha256:543d23d1487d1c2d9893061149387a3c63ca413079eb0e487b87f5bea798f3fe
Status: Downloaded newer image for mockserver/mockserver:5.13.2
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2022-08-22 09:17:01 5.13.2 INFO using environment variables:

  [
  	SERVER_PORT=1080
  ]

 and system properties:

  [
  	mockserver.propertyFile=/config/mockserver.properties
  ]

 and command line options:

  [

  ]

2022-08-22 09:17:03 5.13.2 INFO logger level is INFO, change using:
 - 'ConfigurationProperties.logLevel(String level)' in Java code,
 - '-logLevel' command line argument,
 - 'mockserver.logLevel' JVM system property or,
 - 'mockserver.logLevel' property value in 'mockserver.properties'
2022-08-22 09:17:03 5.13.2 INFO 1080 started on port: 1080
```

Image with arm support:

```
➜ docker run mockserver/mockserver:5.14.0
Unable to find image 'mockserver/mockserver:5.14.0' locally
5.14.0: Pulling from mockserver/mockserver
0a602d5f6ca3: Pull complete
d7fbeaa2da3f: Pull complete
a1f1879bb7de: Pull complete
2afd560bd3d9: Pull complete
8a4811140f89: Pull complete
d72616bd414f: Pull complete
004a8328e2b7: Pull complete
Digest: sha256:59bf7fc611dc212f9fe07d316641bceec758f5db06df3d1ba9ac65e3569c805b
Status: Downloaded newer image for mockserver/mockserver:5.14.0
2022-08-22 09:17:57 5.14.0 INFO using environment variables:

  [
  	SERVER_PORT=1080
  ]

 and system properties:

  [
  	mockserver.propertyFile=/config/mockserver.properties
  ]

 and command line options:

  [

  ]

2022-08-22 09:17:58 5.14.0 INFO logger level is INFO, change using:
 - 'ConfigurationProperties.logLevel(String level)' in Java code,
 - '-logLevel' command line argument,
 - 'mockserver.logLevel' JVM system property or,
 - 'mockserver.logLevel' property value in 'mockserver.properties'
2022-08-22 09:17:58 5.14.0 INFO 1080 started on port: 1080
```
