### ISSUE TITLE
mockserver-netty slower after upgrading from 5.11.0 to 5.11.1

### ISSUE THREAD

**Issue by Hakky54** [mock-server/mockserver#837] opened 2020-09-07 14:09 UTC
**Describe the issue**
After upgrading the mocker server library I noticed that the performance dropped of stopping and starting a new server during my unit tests

Before upgrading the library overall build time of my maven project: 100 seconds
After upgrading the library overall build time of my maven project: 148 seconds

**What you are trying to do**
I have a client and a server communicating with each-other. Some unit tests I mocked it with mockito. Other unit tests I mocked it with mockserver-netty. I already use it for couple of months.

**MockServer version**
version 5.11.0 and 5.11.1

**To Reproduce**
Steps to reproduce the issue:
1. Clone the following project: https://github.com/Hakky54/mutual-tls-ssl
2. execute `mvn clean install` from the root directory and note down the build execution time when it finishes
3. bump the mockserver-netty version in the root pom
4. again execute `mvn clean install` from the root directory and note down the build execution time when it finishes
5. compare the two build execution times

**Expected behaviour**
That the performance shouldn't drop after updating the mockerver dependency

**MockServer Log**
before upgrading
```
15:57:47.647 [MockServer-EventLog0] INFO  org.mockserver.log.MockServerEventLog - creating expectation:

  {
    "id" : "0ebcb7a1-40d1-4c8b-8f8a-462d243e948f",
    "priority" : 0,
    "httpRequest" : {
      "method" : "GET",
      "path" : "/api/hello",
      "headers" : {
        "client-type" : [ "ktor apache httpclient" ]
      }
    },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpResponse" : {
      "statusCode" : 200,
      "body" : "Hello"
    }
  }

15:57:47.964 [MockServer-EventLog0] INFO  org.mockserver.log.MockServerEventLog - received request:

  {
    "method" : "GET",
    "path" : "/api/hello",
    "headers" : {
      "client-type" : [ "ktor apache httpclient" ],
      "Accept-Charset" : [ "UTF-8" ],
      "Accept" : [ "*/*" ],
      "User-Agent" : [ "Ktor client" ],
      "Host" : [ "localhost:8080" ],
      "Connection" : [ "Keep-Alive" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  }

15:57:47.969 [MockServer-EventLog0] INFO  org.mockserver.log.MockServerEventLog - request:

  {
    "method" : "GET",
    "path" : "/api/hello",
    "headers" : {
      "client-type" : [ "ktor apache httpclient" ],
      "Accept-Charset" : [ "UTF-8" ],
      "Accept" : [ "*/*" ],
      "User-Agent" : [ "Ktor client" ],
      "Host" : [ "localhost:8080" ],
      "Connection" : [ "Keep-Alive" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  }

 matched expectation:

  {
    "id" : "0ebcb7a1-40d1-4c8b-8f8a-462d243e948f",
    "priority" : 0,
    "httpRequest" : {
      "method" : "GET",
      "path" : "/api/hello",
      "headers" : {
        "client-type" : [ "ktor apache httpclient" ]
      }
    },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpResponse" : {
      "statusCode" : 200,
      "body" : "Hello"
    }
  }

15:57:47.972 [MockServer-EventLog0] INFO  org.mockserver.log.MockServerEventLog - returning response:

  {
    "statusCode" : 200,
    "body" : "Hello"
  }

 for request:

  {
    "method" : "GET",
    "path" : "/api/hello",
    "headers" : {
      "client-type" : [ "ktor apache httpclient" ],
      "Accept-Charset" : [ "UTF-8" ],
      "Accept" : [ "*/*" ],
      "User-Agent" : [ "Ktor client" ],
      "Host" : [ "localhost:8080" ],
      "Connection" : [ "Keep-Alive" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  }

 for action:

  {
    "statusCode" : 200,
    "body" : "Hello"
  }

```

after upgrading:
```
16:00:26.715 [MockServer-EventLog0] INFO  org.mockserver.log.MockServerEventLog - 8080 creating expectation:

  {
    "id" : "6c37d6d2-1b82-45dd-a0b9-701f81ffc1d3",
    "priority" : 0,
    "httpRequest" : {
      "method" : "GET",
      "path" : "/api/hello",
      "headers" : {
        "client-type" : [ "ktor apache httpclient" ]
      }
    },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpResponse" : {
      "statusCode" : 200,
      "body" : "Hello"
    }
  }

 with id:

  6c37d6d2-1b82-45dd-a0b9-701f81ffc1d3

16:00:27.014 [MockServer-EventLog0] INFO  org.mockserver.log.MockServerEventLog - 8080 received request:

  {
    "method" : "GET",
    "path" : "/api/hello",
    "headers" : {
      "client-type" : [ "ktor apache httpclient" ],
      "Accept-Charset" : [ "UTF-8" ],
      "Accept" : [ "*/*" ],
      "User-Agent" : [ "Ktor client" ],
      "Host" : [ "localhost:8080" ],
      "Connection" : [ "Keep-Alive" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  }

16:00:27.019 [MockServer-EventLog0] INFO  org.mockserver.log.MockServerEventLog - 8080 request:

  {
    "method" : "GET",
    "path" : "/api/hello",
    "headers" : {
      "client-type" : [ "ktor apache httpclient" ],
      "Accept-Charset" : [ "UTF-8" ],
      "Accept" : [ "*/*" ],
      "User-Agent" : [ "Ktor client" ],
      "Host" : [ "localhost:8080" ],
      "Connection" : [ "Keep-Alive" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  }

 matched expectation:

  {
    "id" : "6c37d6d2-1b82-45dd-a0b9-701f81ffc1d3",
    "priority" : 0,
    "httpRequest" : {
      "method" : "GET",
      "path" : "/api/hello",
      "headers" : {
        "client-type" : [ "ktor apache httpclient" ]
      }
    },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpResponse" : {
      "statusCode" : 200,
      "body" : "Hello"
    }
  }

16:00:27.023 [MockServer-EventLog0] INFO  org.mockserver.log.MockServerEventLog - 8080 returning response:

  {
    "statusCode" : 200,
    "body" : "Hello"
  }

 for request:

  {
    "method" : "GET",
    "path" : "/api/hello",
    "headers" : {
      "client-type" : [ "ktor apache httpclient" ],
      "Accept-Charset" : [ "UTF-8" ],
      "Accept" : [ "*/*" ],
      "User-Agent" : [ "Ktor client" ],
      "Host" : [ "localhost:8080" ],
      "Connection" : [ "Keep-Alive" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  }

 for action:

  {
    "statusCode" : 200,
    "body" : "Hello"
  }

 from expectation:

  6c37d6d2-1b82-45dd-a0b9-701f81ffc1d3

16:00:27.111 [MockServer-EventLog0] INFO  org.mockserver.log.MockServerEventLog - stopped for port: 8080
```

**Comment by jamesdbloom** [comment] 2020-09-11 08:20
I may have an idea what has caused this. I'll take a look.

**Comment by jamesdbloom** [comment] 2020-09-11 08:20
I think it may be fixed in the SNAPSHOT version but I'll test it myself.

**Comment by Hakky54** [comment] 2020-09-11 09:33
Glad to hear, thank you for investigating it! Let me know if I should do or try something out on my side

**Comment by jamesdbloom** [comment] 2020-09-11 12:36
The latest SNAPSHOT has some fixes to resolve this issue.  However this was largely caused by calling stop 4 times in a row.  Each stop added additional work on the scheduler delaying the stop.  From my measurements the code has gone from 4 s to 100 ms to stop the MockServer.  I have made additional change in the latest SNAPSHOT to stop an unfortunate recursion and other more recent performance improvements.  

I have raised a PR to fix the code in https://github.com/Hakky54/mutual-tls-ssl/pull/75 to avoid the issue in 5.11.1 but using 5.11.2 will further improve performance once this is released.

**Closed by jamesdbloom** 2020-09-11 12:36 UTC
Labels: bug

**Comment by Hakky54** [comment] 2020-09-11 14:30
Thank you, it looks like I was not using the library properly. And thank you for the pull request, it has now the same performance with version 5.11.1 🥳 🎉 

By the way do you recommend to initialize/start the server during every single unit test and stop it at the end of each unit test, just how it is used right now within the mutual-tls-ssl project, or do you recommend to just start it once before all the unit test and supply it with  RequestDeifnitions during each unit test. And stop the mockerserver at the end of the unit test suite?

**Comment by jamesdbloom** [comment] 2020-09-12 05:06
I would suggest for performance you could start it once at the beginning and reset between each test but only if you don't want to ever run your tests in parallel.  Another options is to use a separate identifier for each test, for example a correlationId header (if you already have such a thing).  If you don't have such a test unique identifier then running a separate instance per test is fine and this will allow you to run your tests in parallel which should give you the shortest build speed.
