### ISSUE TITLE
Missing documentation on forwarding

### ISSUE THREAD

**Issue by madduci** [mock-server/mockserver#813] opened 2020-07-15 08:18 UTC
**Describe the issue**
I haven't find a way to use forwarding of requests in case a service returns the header 'Location' set and return code 302/303.

**What you are trying to do**
I have a proxy service that takes requests and forwards them to other existing services, we call them A, B and C. One of this services, let's say A, returns a 30x code with the header "Location" set to another service, B. Unfortunately, the test waits until it receives a timeout.

**MockServer version**
5.11.0

**To Reproduce**
Steps to reproduce the issue:

1. Initialize Mock-Server in Java code
2.
```
   mockServer = ClientAndServer.startClientAndServer( 20443 ).withSecure( true );
    Assertions.assertTrue( mockServer.hasStarted() );

    System.out.println( "#### Mock server running on " + mockServer.getPort() );

    mockServer.when( request().withSocketAddress( "localhost", 4321, SocketAddress.Scheme.HTTP ).withPath( "/sp/.*" ) )
              .forward( HttpForward.forward().withHost( "localhost" ).withPort( 4321 ).withScheme( HttpForward.Scheme.HTTP ) );
    mockServer.when( request().withSocketAddress( "localhost", 4321, SocketAddress.Scheme.HTTPS ).withPath( "/sp/.*" ) )
              .forward( HttpForward.forward().withHost( "localhost" ).withPort( 4321 ).withScheme( HttpForward.Scheme.HTTPS ) );

    mockServer.when( request().withSocketAddress( "localhost", 1254, SocketAddress.Scheme.HTTPS ).withPath( "/" ) )
              .forward( HttpForward.forward().withHost( "localhost" ).withPort( 1254 ).withScheme( HttpForward.Scheme.HTTPS ) );

    mockServer.when( request().withSocketAddress( "localhost", 6789, SocketAddress.Scheme.HTTP ).withPath( "/id.*" ) )
              .forward( HttpForward.forward().withHost( "localhost" ).withPort( 6789 ).withScheme( HttpForward.Scheme.HTTP ) );

```
3. The connection goes in timeout after the redirect with 'Location'

**Expected behaviour**
A way to wire the proxy services A, B and C with redirects.

**MockServer Log**
Cannot provide it unfortunately

**Comment by jamesdbloom** [comment] 2020-07-16 19:30
I'm afraid I don't understand what you are trying to do or where your issue is.  I have tested that if MockServer is setup with an expectation that returns a 302 redirect that works correctly.  I have also tested if MockServer forwards a request to an endpoint that returns a 302 redirect this is returned exactly as the endpoint returned it.  MockServer does not follow redirects because this would take away the ability of the client calling MockServer to decide whether redirects are followed or not.

Can you please provide some more context around what you are trying to do and what is returning the 302 redirect.  I suspect if you test is waiting until it hits a timeout then your test client is not handling redirects.

**Comment by madduci** [comment] 2020-07-17 03:34
Hi

I reformulate the scenario: I have configured global Java settings for proxy and a plain Java URL Connection that I open towards one of the services as explained previously. Specifically, one of those services replies with a redirect to another location, thus the header "Location": "serviceB", which causes the timeout, since, as you mentioned, there's no follow on redirect from MockServer. 

My question is: is there a way to pass back to my client the redirect information (the reply with 302/303 and the header location) in the context of a forward rule, so that the client takes care of it? It's worth mentioning that without MockServer, the client and the services work as expected.

**Comment by jamesdbloom** [comment] 2020-07-17 06:14
I have reproduced the following scenario without any issue, as below:

The scenario is:

```java
// 1070: forwards -> 1080
// 1080: redirects -> 1090
// 1090: returns: 200: [redirected_body]
```

This demonstrates your scenario as I understand it.  Can you please modify my code to demonstrate the issue you are having.  

**Note:** `HttpURLConnection` automatically follows the redirect returned by 1070 (which was returned by 1080 after the request was forwarded from 1070 to 1080).

**Note:** the logging of the port at the start of each log line is something I added to easily debug this scenario.  This will be in the next release to help debugging any similar type of issue with multiple instances of MockServer talking between them.

```java
package org.mockserver.examples;

import org.apache.commons.io.IOUtils;
import org.mockserver.integration.ClientAndServer;

import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;

import static org.mockserver.model.HttpForward.forward;
import static org.mockserver.model.HttpRequest.request;
import static org.mockserver.model.HttpResponse.response;

public class Issue813 {
    public static void main(String[] args) throws IOException {
        new ClientAndServer(1070)
            .when(
                request()
            )
            .forward(
                forward()
                    .withHost("localhost")
                    .withPort(1080)
            );

        new ClientAndServer(1080)
            .when(request())
            .respond(
                response()
                    .withStatusCode(302)
                    .withHeader("Location", "http://localhost:1090/redirected")
            );

        new ClientAndServer(1090)
            .when(
                request()
                    .withPath("/redirected")
            )
            .respond(
                response()
                    .withBody("redirected_body", StandardCharsets.UTF_8)
            );

        // 1070: forwards -> 1080
        // 1080: redirects -> 1090
        // 1090: returns: 200: [redirected_body]

        HttpURLConnection con = (HttpURLConnection) new URL("http://localhost:1070/redirected").openConnection();
        con.setRequestMethod("GET");
        if (con.getErrorStream() != null) {
            System.out.println("error response " + con.getResponseCode() + ": " + IOUtils.readLines(con.getErrorStream(), StandardCharsets.UTF_8));
        } else if (con.getResponseCode() != 404) {
            System.out.println("success response " + con.getResponseCode() + ": " + IOUtils.readLines(con.getInputStream(), StandardCharsets.UTF_8));
        } else {
            System.out.println("not found response");
        }
        con.disconnect();
    }
}
```

Log output:

```bash
2020-07-17 07:07:47 5.11.1-SNAPSHOT INFO  1070 started on port: 1070 
2020-07-17 07:07:48 5.11.1-SNAPSHOT INFO  1070 creating expectation:

  {
    "id" : "bb5e143a-f599-4703-8652-6336a0ff8e6c",
    "priority" : 0,
    "httpRequest" : { },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpForward" : {
      "host" : "localhost",
      "port" : 1080,
      "scheme" : "HTTP"
    }
  }
 
2020-07-17 07:07:48 5.11.1-SNAPSHOT INFO  1080 started on port: 1080 
2020-07-17 07:07:48 5.11.1-SNAPSHOT INFO  1080 creating expectation:

  {
    "id" : "ccd649a1-a32f-4c9c-964a-cb691fc53e5e",
    "priority" : 0,
    "httpRequest" : { },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpResponse" : {
      "statusCode" : 302,
      "headers" : {
        "Location" : [ "http://localhost:1090/redirected" ]
      }
    }
  }
 
2020-07-17 07:07:48 5.11.1-SNAPSHOT INFO  1090 started on port: 1090 
2020-07-17 07:07:48 5.11.1-SNAPSHOT INFO  1090 creating expectation:

  {
    "id" : "41f2a505-d375-4f5c-9ec2-c2b5efa91708",
    "priority" : 0,
    "httpRequest" : {
      "path" : "/redirected"
    },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpResponse" : {
      "body" : {
        "type" : "STRING",
        "string" : "redirected_body",
        "contentType" : "text/plain; charset=utf-8"
      }
    }
  }
 
2020-07-17 07:07:48 5.11.1-SNAPSHOT INFO  1070 received request:

  {
    "method" : "GET",
    "path" : "/redirected",
    "headers" : {
      "User-Agent" : [ "Java/1.8.0_201" ],
      "Host" : [ "localhost:1070" ],
      "Accept" : [ "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2" ],
      "Connection" : [ "keep-alive" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false,
    "socketAddress" : {
      "host" : "localhost",
      "port" : 1070,
      "scheme" : "HTTP"
    }
  }
 
2020-07-17 07:07:48 5.11.1-SNAPSHOT INFO  1070 request:

  {
    "method" : "GET",
    "path" : "/redirected",
    "headers" : {
      "User-Agent" : [ "Java/1.8.0_201" ],
      "Host" : [ "localhost:1070" ],
      "Accept" : [ "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2" ],
      "Connection" : [ "keep-alive" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false,
    "socketAddress" : {
      "host" : "localhost",
      "port" : 1070,
      "scheme" : "HTTP"
    }
  }

 matched expectation:

  {
    "id" : "bb5e143a-f599-4703-8652-6336a0ff8e6c",
    "priority" : 0,
    "httpRequest" : { },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpForward" : {
      "host" : "localhost",
      "port" : 1080,
      "scheme" : "HTTP"
    }
  }
 
2020-07-17 07:07:48 5.11.1-SNAPSHOT INFO  1080 received request:

  {
    "method" : "GET",
    "path" : "/redirected",
    "headers" : {
      "User-Agent" : [ "Java/1.8.0_201" ],
      "Accept" : [ "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2" ],
      "host" : [ "localhost:1070" ],
      "accept-encoding" : [ "gzip,deflate" ],
      "content-length" : [ "0" ],
      "connection" : [ "keep-alive" ]
    },
    "keepAlive" : true,
    "secure" : false,
    "socketAddress" : {
      "host" : "localhost",
      "port" : 1080,
      "scheme" : "HTTP"
    }
  }
 
2020-07-17 07:07:48 5.11.1-SNAPSHOT INFO  1080 request:

  {
    "method" : "GET",
    "path" : "/redirected",
    "headers" : {
      "User-Agent" : [ "Java/1.8.0_201" ],
      "Accept" : [ "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2" ],
      "host" : [ "localhost:1070" ],
      "accept-encoding" : [ "gzip,deflate" ],
      "content-length" : [ "0" ],
      "connection" : [ "keep-alive" ]
    },
    "keepAlive" : true,
    "secure" : false,
    "socketAddress" : {
      "host" : "localhost",
      "port" : 1080,
      "scheme" : "HTTP"
    }
  }

 matched expectation:

  {
    "id" : "ccd649a1-a32f-4c9c-964a-cb691fc53e5e",
    "priority" : 0,
    "httpRequest" : { },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpResponse" : {
      "statusCode" : 302,
      "headers" : {
        "Location" : [ "http://localhost:1090/redirected" ]
      }
    }
  }
 
2020-07-17 07:07:48 5.11.1-SNAPSHOT INFO  1080 returning response:

  {
    "statusCode" : 302,
    "headers" : {
      "Location" : [ "http://localhost:1090/redirected" ]
    }
  }

 for request:

  {
    "method" : "GET",
    "path" : "/redirected",
    "headers" : {
      "User-Agent" : [ "Java/1.8.0_201" ],
      "Accept" : [ "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2" ],
      "host" : [ "localhost:1070" ],
      "accept-encoding" : [ "gzip,deflate" ],
      "content-length" : [ "0" ],
      "connection" : [ "keep-alive" ]
    },
    "keepAlive" : true,
    "secure" : false,
    "socketAddress" : {
      "host" : "localhost",
      "port" : 1080,
      "scheme" : "HTTP"
    }
  }

 for action:

  {
    "statusCode" : 302,
    "headers" : {
      "Location" : [ "http://localhost:1090/redirected" ]
    }
  }
 
2020-07-17 07:07:48 5.11.1-SNAPSHOT INFO  1070 returning response:

  {
    "statusCode" : 302,
    "reasonPhrase" : "Found",
    "headers" : {
      "Location" : [ "http://localhost:1090/redirected" ],
      "connection" : [ "keep-alive" ],
      "content-length" : [ "0" ]
    }
  }

 for forwarded request

 in json:

  {
    "method" : "GET",
    "path" : "/redirected",
    "headers" : {
      "User-Agent" : [ "Java/1.8.0_201" ],
      "Host" : [ "localhost:1070" ],
      "Accept" : [ "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2" ],
      "Connection" : [ "keep-alive" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false,
    "socketAddress" : {
      "host" : "localhost",
      "port" : 1070,
      "scheme" : "HTTP"
    }
  }

 

 in curl:

  curl -v 'http://localhost:1070/redirected' -H 'User-Agent: Java/1.8.0_201' -H 'Host: localhost:1070' -H 'Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2' -H 'Connection: keep-alive' -H 'content-length: 0'

 for action:

  {
    "host" : "localhost",
    "port" : 1080,
    "scheme" : "HTTP"
  }
 
2020-07-17 07:07:48 5.11.1-SNAPSHOT INFO  1090 received request:

  {
    "method" : "GET",
    "path" : "/redirected",
    "headers" : {
      "User-Agent" : [ "Java/1.8.0_201" ],
      "Host" : [ "localhost:1090" ],
      "Accept" : [ "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2" ],
      "Connection" : [ "keep-alive" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false,
    "socketAddress" : {
      "host" : "localhost",
      "port" : 1090,
      "scheme" : "HTTP"
    }
  }
 
2020-07-17 07:07:48 5.11.1-SNAPSHOT INFO  1090 request:

  {
    "method" : "GET",
    "path" : "/redirected",
    "headers" : {
      "User-Agent" : [ "Java/1.8.0_201" ],
      "Host" : [ "localhost:1090" ],
      "Accept" : [ "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2" ],
      "Connection" : [ "keep-alive" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false,
    "socketAddress" : {
      "host" : "localhost",
      "port" : 1090,
      "scheme" : "HTTP"
    }
  }

 matched expectation:

  {
    "id" : "41f2a505-d375-4f5c-9ec2-c2b5efa91708",
    "priority" : 0,
    "httpRequest" : {
      "path" : "/redirected"
    },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpResponse" : {
      "body" : {
        "type" : "STRING",
        "string" : "redirected_body",
        "contentType" : "text/plain; charset=utf-8"
      }
    }
  }
 
2020-07-17 07:07:48 5.11.1-SNAPSHOT INFO  1090 returning response:

  {
    "body" : "redirected_body"
  }

 for request:

  {
    "method" : "GET",
    "path" : "/redirected",
    "headers" : {
      "User-Agent" : [ "Java/1.8.0_201" ],
      "Host" : [ "localhost:1090" ],
      "Accept" : [ "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2" ],
      "Connection" : [ "keep-alive" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false,
    "socketAddress" : {
      "host" : "localhost",
      "port" : 1090,
      "scheme" : "HTTP"
    }
  }

 for action:

  {
    "body" : "redirected_body"
  }
 
success response 200: [redirected_body]

Process finished with exit code 0
```

**Comment by jamesdbloom** [comment] 2020-07-17 06:19
FYI shortly I'm going to add this code into the project as a class called `org.mockserver.examples.mockserver.RedirectBetweenMultiMockServerInstances`.  Also later this morning I'll push the change to log the port numbers at the start of log lines to the SNAPSHOT, see: https://mock-server.com/where/maven_central.html#sonatype_snapshot

**Comment by madduci** [comment] 2020-07-17 06:55
I see you've instantiated 3 MockServers, one for each service to be hidden by a proxy, but I've used only one MockServer as Proxy and multiple forward rules, just like this [picture](https://www.mock-server.com/images/recording_requests_with_mockserver_proxy.png).

The JVM is configured with:

https.proxyHost = "localhost"
https.proxyPort =  String.valueOf(mockserver.getPort())

just to be clear.

**Comment by jamesdbloom** [comment] 2020-07-17 07:43
I've used three MockServer instance because I don't have your service to simulate your entire scenario, not for anything other reason.

Can you please instances of MockServer to reproduce your scenario, because I'm assuming it is not feasible or practical to provide a reproducer with your entire service.

**Comment by madduci** [comment] 2020-07-17 08:41
I see.
Unfortunately I can't, since the scenario and the roles involved I'm working with is pretty complex. What I need is a kind of proxy-pass that emulates just sends all the received requests to the services I want to communicate with, like a "man-in-the-middle". As said, one of the behind-the-proxy service looks like can't move to the other behind-the-proxy service, probably because of JVM proxy values.

**Comment by jamesdbloom** [comment] 2020-07-17 09:30
Current there is no support for apache style [proxypass](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html) rules.  Without such a support then it wouldn't make sense to follow redirections because the response would be invalid.  However, adding support for proxypass is on the backlog https://trello.com/c/2IjJ5e27/67-apache-style-simple-proxypass-functionality.

**Comment by madduci** [comment] 2020-07-17 09:31
ok thanks!

**Closed** 2020-07-22 06:19 UTC
Labels: need_more_information, unable_to_reproduce
