### ISSUE TITLE
SSLException: Received close_notify during handshake

### ISSUE THREAD

**Issue by pbukhon** [mock-server/mockserver#457] opened 2018-04-04 08:07 UTC
Hi.
I'd like to use MoskServer for my iOs application to mock ad responses. It's working fine for most of ad services that I'm using but there is a problem with Mopub and Facebook. 
When I mock request for Mopub server gives message that Expectation matched and looks like everything fine, But next message is 

2018-04-04 10:52:47,406 WARN o.m.u.PortUnificationHandler Exception caught by port unification handler -> closing pipeline [id: 0x7b3b632c, L:0.0.0.0/0.0.0.0:1090 ! R:/192.168.1.70:64719]
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received close_notify during handshake

Can it be a cause of no ad received?
Thanks

**Comment by jamesdbloom** [comment] 2019-11-16 13:37
A related issue is #405 that issue is now closed as a duplicate of this issue.

However, in that issue, it looks like the error was caused by trust not being correctly configured for the MockServer CA certificate so that it was a trusted signing certificate? If a client does not trust the MockServer CA certificate then it likely it is closing the socket before the TLS handshake has been completed thus the error you've seen.

Can you please confirm Mopub and Facebook is correctly configured to trust the MockServer CA certificate, or even supports this.  It is possible Facebook, for example, is using CA certificate pinning making it impossible to do a man-in-the-middle or spoof their servers because the Facebook application would be expecting all TLS certificates to be signed by a specific CA certificate and there would be no way to reconfigure this.

**Comment by jamesdbloom** [comment] 2019-12-01 07:17
@pbukhon Is there any update on this?

**Closed** 2019-12-04 14:31 UTC
Labels: need_more_information, question
