### ISSUE TITLE
Initialize MockServer from OpenApi (Swagger) Schema

### ISSUE THREAD

**Issue by msnookxom** [mock-server/mockserver#768] opened 2020-04-16 01:35 UTC
**Describe the feature request**

Is it possible to initialize the MockServer using an OpenAPI (Swagger) file?

**What you are trying to do**

Trying to initialize the Mock Server using an OpenAPI (Swagger) `json` file.

**The solution you'd like**

Can an OpenAPI (Swagger) `json` file be used as an Expectation Initializer?

**Describe alternatives you've considered**

N/A

**Comment by jamesdbloom** [comment] 2020-07-07 03:37
This is now implemented and will be released in the next couple of days, also this issue is a duplicate of #550.

**Closed by jamesdbloom** 2020-07-07 03:37 UTC
Labels: enhancement
