### ISSUE TITLE
mockserver-netty doesn't stop correctly

### ISSUE THREAD

**Issue by anilkumarmyla** [mock-server/mockserver#708] opened 2019-12-12 17:32 UTC
**Describe the issue**
mockserver-netty doesn't stop correctly

**What you are trying to do**
Setting up a mock server during unit tests and exercising unit tests

**MockServer version**
5.8.0

**To Reproduce**
Steps to reproduce the issue:

1. How you are running MockServer (i.e maven plugin, docker, etc)
```
setup:
server = startClientAndServer(port)

teardown:
server.stop()
```

2. Starting with mockserver-netty-5.7.0, the mock server stops asynchronously even though we explicitly run server.stop() leading to subsequent requests hitting the mockserver when they shouldn't

When run through sbt, we see this clearly
```
[warn] Thread[MockServer-ClientAndServer-eventLoop2,5,main] loading io.netty.channel.AbstractChannel$AbstractUnsafe$5 after test or run has completed. This is a likely resource leak
```

**Expected behaviour**
when server.stop() is called, it shouldn't return back to the caller until the event loop is closed correctly

**MockServer Log**
```
[info] Waiting for measurement data to sync...
[warn] Thread[MockServer-ClientAndServer-eventLoop2,5,main] loading io.netty.channel.AbstractChannel$AbstractUnsafe$5 after test or run has completed. This is a likely resource leak
[info] Reading scoverage instrumentation 
[info] Reading scoverage measurements...
2019-12-12 23:00:23.827 - [DEBUG] - from io.netty.buffer.PoolThreadCache-249 Freed 3 thread-local buffer(s) from thread: MockServer-ClientAndServer-eventLoop6
2019-12-12 23:00:23.827 - [DEBUG] - from io.netty.buffer.PoolThreadCache-249 Freed 4 thread-local buffer(s) from thread: MockServer-ClientAndServer-eventLoop8
2019-12-12 23:00:23.827 - [DEBUG] - from io.netty.buffer.PoolThreadCache-249 Freed 3 thread-local buffer(s) from thread: MockServer-ClientAndServer-eventLoop10
[info] Generating scoverage reports...
```

**Comment by jamesdbloom** [comment] 2019-12-22 07:10
There are three stop methods:
```java
stopAsync - which returns a future for when MockServer has stopped
stop - which blocks until MockServer has stopped
stop(boolean ignoreFailure) - which returns a future for when MockServer has stopped
```
**Can you please explain which of these are being used and exactly why you think MockServer is still accepting requests?**

**Are you sure your test framework is executing the methods in the order you expect?**

The following code demonstrates this behaviour working correctly:
```java
import io.netty.channel.EventLoopGroup;
import io.netty.channel.nio.NioEventLoopGroup;
import org.mockserver.client.NettyHttpClient;
import org.mockserver.integration.ClientAndServer;
import org.mockserver.logging.MockServerLogger;
import org.mockserver.scheduler.Scheduler;

import java.net.InetSocketAddress;
import java.util.concurrent.ExecutionException;

import static org.mockserver.integration.ClientAndServer.startClientAndServer;
import static org.mockserver.model.HttpRequest.request;

public class Issue708 {

    private static final EventLoopGroup eventLoopGroup = new NioEventLoopGroup(0, new Scheduler.SchedulerThreadFactory(Issue708.class.getSimpleName() + "-eventLoop"));

    public static void main(String[] args) throws InterruptedException, ExecutionException {
        System.out.println("SENDING REQUEST THAT WILL ERROR");

        try {
            new NettyHttpClient(new MockServerLogger(), eventLoopGroup, null)
                .sendRequest(request(), new InetSocketAddress(1080))
                .get();
        } catch (Throwable throwable) {
            System.out.println("Expected connection error:" + throwable);
        }

        System.out.println("STARTING MOCKSERVER");

        ClientAndServer clientAndServer = startClientAndServer(1080);

        System.out.println("SENDING REQUEST");

        new NettyHttpClient(new MockServerLogger(), eventLoopGroup, null)
            .sendRequest(request(), new InetSocketAddress(1080))
            .get();

        System.out.println("STOPPING MOCKSERVER - note: any remaining log entries are written out");

        clientAndServer.stop();

        System.out.println("SENDING REQUEST THAT WILL ERROR");

        try {
            new NettyHttpClient(new MockServerLogger(), eventLoopGroup, null)
                .sendRequest(request(), new InetSocketAddress(1080))
                .get();
        } catch (Throwable throwable) {
            System.out.println("Expected connection error:" + throwable);
        }
    }
}
```

And the log output:

```bash
SENDING REQUEST THAT WILL ERROR
Expected connection error:java.util.concurrent.ExecutionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 0.0.0.0/0.0.0.0:1080
STARTING MOCKSERVER
SENDING REQUEST
2019-12-22 07:08:25  org.mockserver.log.MockServerEventLog  INFO  started on port: 1080 
2019-12-22 07:08:25  org.mockserver.log.MockServerEventLog  INFO  received request:

	{
	  "method" : "GET",
	  "path" : "/",
	  "headers" : {
	    "accept-encoding" : [ "gzip,deflate" ],
	    "content-length" : [ "0" ],
	    "connection" : [ "keep-alive" ]
	  },
	  "keepAlive" : true,
	  "secure" : false
	}
 
STOPPING MOCKSERVER - note: any remaining log entries are written out
2019-12-22 07:08:25  org.mockserver.log.MockServerEventLog  INFO  no expectation for:

	{
	  "method" : "GET",
	  "path" : "/",
	  "headers" : {
	    "accept-encoding" : [ "gzip,deflate" ],
	    "content-length" : [ "0" ],
	    "connection" : [ "keep-alive" ]
	  },
	  "keepAlive" : true,
	  "secure" : false
	}

 returning response:

	{
	  "statusCode" : 404,
	  "reasonPhrase" : "Not Found"
	}
 
SENDING REQUEST THAT WILL ERROR
Expected connection error:java.util.concurrent.ExecutionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 0.0.0.0/0.0.0.0:1080
```

**Comment by anilkumarmyla** [comment] 2019-12-24 07:29
Hmm, on a first glance ClientAndServer.java calls the 3rd option (future) even though the return type is void. So there is a chance that the server is still running even calling `ClientAndServer .stop()`

```
    @Override
    public void stop() {
        mockServer.stop();
        stop(true);
    }
```

**Comment by jamesdbloom** [comment] 2019-12-24 07:39
good point, I'll fix that

**Comment by jamesdbloom** [comment] 2020-01-31 06:53
Closing issue as can't reproduce on the current codebase.

**Closed by jamesdbloom** 2020-01-31 06:53 UTC
Labels: need_more_information, unable_to_reproduce

**Comment by DanielJoyce** [comment] 2020-08-03 22:31
We're seeing this behavior in 5.11.1 with testNg which mockServer.stop() failing to shut down completely in @AfterMethod before a new instance on the same port is started again in @BeforeMethod

**Comment by miguel-figueiredo** [comment] 2020-08-04 12:53
We are getting this issue when running with Quarkus tests, and having responses with delays. Also in version 5.11.1.

**Comment by mkemmerz** [comment] 2020-10-08 09:04
We are also having issues with stopping our server with the veresion 5.11.1. In some cases it takes very very long.
