### ISSUE TITLE
Follow-up: "bad record MAC" error when HTTP CONNECT proxying HTTPS from a Golang client

### ISSUE THREAD

**Issue by rtkamorozov** [mock-server/mockserver#726] opened 2020-02-13 13:57 UTC
Sorry for the dupe, but I am unable to reopen the existing ticket (a GH permission issue?)

This is a follow-up on #717. Please feel free to close this one and reopen the old card.

I have had a chance to try `5.9.0` out and, unfortunately, it does not seem to have resolved the issue.

Also, I noticed a caveat in the Go code you used to test the proxy. The gotcha is that when you use the custom transport configuration, Go won't read the `HTTP*_PROXY` variables and will rely on whatever is explicitly specified in code.

Here is the updated code that accounts for the `HTTPS_PROXY` var.

```
package main

import (
	"crypto/tls"
	"crypto/x509"
	"flag"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"net/url"
	"os"
)

const (
	localCertFile = "./ca.pem"
)

func main() {
	insecure := flag.Bool("insecure-ssl", false, "Accept/Ignore all server SSL certificates")
	flag.Parse()

	// Get the SystemCertPool, continue with an empty pool on error
	rootCAs, _ := x509.SystemCertPool()
	if rootCAs == nil {
		rootCAs = x509.NewCertPool()
	}

	// Read in the cert file
	certs, err := ioutil.ReadFile(localCertFile)
	if err != nil {
		log.Fatalf("Failed to append %q to RootCAs: %v", localCertFile, err)
	}

	// Append our cert to the system pool
	if ok := rootCAs.AppendCertsFromPEM(certs); !ok {
		log.Println("No certs appended, using system certs only")
	}

	// Trust the augmented cert pool in our client
	config := &tls.Config{
		InsecureSkipVerify: *insecure,
		RootCAs:            rootCAs,
	}
	tr := &http.Transport{
		TLSClientConfig: config,
		Proxy: func(request *http.Request) (url *url.URL, e error) {
			proxyString := os.Getenv("HTTPS_PROXY")
			if proxyString == "" {
				log.Fatal("Set the HTTP_PROXY env variable")
			}
			return url.Parse(proxyString)
		},
	}
	client := &http.Client{Transport: tr}

	req, err := http.NewRequest(http.MethodGet, "https://github.com", nil)
	if err != nil {
		panic(err)
	}

	resp, err := client.Do(req)
	if err != nil {
		panic(err)
	}
	fmt.Println(resp.StatusCode)
}
```

I run it with

```
go build 
curl https://raw.githubusercontent.com/mock-server/mockserver/master/mockserver-core/src/main/resources/org/mockserver/socket/CertificateAuthorityCertificate.pem > ca.pem
HTTPS_PROXY=https://localhost:1080 ./compiled_client
```
and
```
HTTPS_PROXY=https://localhost:1080 ./compiled_client --insecure-ssl
``

and am getting the same "bad record MAC" error.

**Comment by jamesdbloom** [comment] 2020-02-15 07:10
This is a really tricky problem to solve because I'm just using the default netty SSL handler, however, I have seen a strange behaviour where the SSL context is created twice.

I'll try and debug this as further and see if I can fix it, but so far there does look like a clear reason why this is happening.  All other clients tested work fine but I do know that golang can be stricter on TLS.  I've had issues before with golang TLS failing where no other clients fail (browsers, node, java and python).

**Comment by jamesdbloom** [comment] 2020-02-16 07:46
I did make one change that seems to change the golang behaviour.  It seems that when golang is making an HTTP CONNECT request over TLS it does like it if a new TLS session is required.  To my understanding, this seems odd because HTTP CONNECT should be enabling a connection to a remote server therefore a new TLS handshake is always required.  So I allowed the original TLS session by not removing and re-adding the netty SslHandler.  I've not found any other client that behaves in this way but it seems harmless to do this.  This changes the error golang returns but there is still an error returned related to not parsing the TLS header correctly.

I'm starting to think there may be a bug in golang with the way it handles HTTP CONNECT requests, for the following reasons:
1. I can't reproduce this error with any other client I've tried including Slack client, MatterMost client, Chrome, Firefox, Microsoft Outlook, YouTube streaming, and java
2. golang does not complain about the TLS connection when not using HTTP CONNECT, i.e. making direct requests
3. there are a lot of people online mentioning issues with "bad record MAC" for golang

I am happy to leave this ticket open for now until there is a better understanding of what is going on here.

**Comment by jamesdbloom** [comment] 2022-03-22 00:30
I have finally tracked down the cause of this issue.  It it because the go client is attempting to use ALPN to switch to HTTP2 so once the HTTP CONNECT request is made it attempts to upgrade the protocol and this fails because MockServer doesn't currently support HTTP2 or ALPN.  This support will however be added and it on the backlog here: https://trello.com/c/vLEEtk5o/16-support-http2-alpn.

It is still possible to use socks5 as the proxy protocol with MockServer from go lang by specifying "socks5://localhost:1080" as the proxyString.

I'm going too close this ticket pending the backlog item: https://trello.com/c/vLEEtk5o/16-support-http2-alpn.

**Closed by jamesdbloom** 2022-03-22 00:30 UTC
Labels: bug
