### ISSUE TITLE
Diacritics returned as "?"

### ISSUE THREAD

**Issue by jastka4** [mock-server/mockserver#723] opened 2020-02-11 15:53 UTC
**Describe the issue**
Diacritics used in the initializerJson.json are changed to "?" instead of being returned as-is.

Also, the POST body seems to be malformed when using diacritics.

**What you are trying to do**
I'm trying to mock an API that returns data in the Polish language.

**MockServer version**
5.9.0

**To Reproduce**
I used a Docker image.

Create a server with a config like this:
```json
[
    {
      "httpRequest": {
        "path": "/test",
        "method": "POST"
      },
      "httpResponse": {
        "statusCode": 200,
        "headers": [
            {
                "name": "Content-Type",
                "values": ["application/json"]
            }
        ],
        "body": "{\"test\":\"zażółć gęślą jaźń\"}"
      }
    }
]
```

This is what I get as a response:
```json
{
    "test": "za?�?? g??l? ja??"
}
```

**Expected behaviour**
I should get this instead:
```json
{
    "test": "zażółć gęślą jaźń"
}
```

**MockServer Log**
Here, you can see the malformed body of the POST request.

```
mockServer_1  | 2020-02-11 15:50:00  org.mockserver.log.MockServerEventLog  INFO  returning response:
mockServer_1  |
mockServer_1  | 	{
mockServer_1  | 	  "statusCode" : 200,
mockServer_1  | 	  "headers" : {
mockServer_1  | 	    "Content-Type" : [ "application/json" ]
mockServer_1  | 	  },
mockServer_1  | 	  "body" : "{\"test\":\"zażółć gęślą jaźń\"}"
mockServer_1  | 	}
mockServer_1  |
mockServer_1  |  for request:
mockServer_1  |
mockServer_1  | 	{
mockServer_1  | 	  "method" : "GET",
mockServer_1  | 	  "path" : "/test",
mockServer_1  | 	  "headers" : {
mockServer_1  | 	    "Content-Type" : [ "application/json" ],
mockServer_1  | 	    "User-Agent" : [ "PostmanRuntime/7.22.0" ],
mockServer_1  | 	    "Accept" : [ "*/*" ],
mockServer_1  | 	    "Cache-Control" : [ "no-cache" ],
mockServer_1  | 	    "Postman-Token" : [ "63db852d-840b-4b51-9ae9-0043ad6364b8" ],
mockServer_1  | 	    "Host" : [ "localhost:1080" ],
mockServer_1  | 	    "Accept-Encoding" : [ "gzip, deflate, br" ],
mockServer_1  | 	    "Content-Length" : [ "41" ],
mockServer_1  | 	    "Connection" : [ "keep-alive" ]
mockServer_1  | 	  },
mockServer_1  | 	  "keepAlive" : true,
mockServer_1  | 	  "secure" : false,
mockServer_1  | 	  "body" : {
mockServer_1  | 	    "test" : "zaÅ¼Ã³ÅÄ gÄÅlÄ	 jaÅºÅ"
mockServer_1  | 	  }
mockServer_1  | 	}
mockServer_1  |
mockServer_1  |  for action:
mockServer_1  |
mockServer_1  | 	{
mockServer_1  | 	  "statusCode" : 200,
mockServer_1  | 	  "headers" : {
mockServer_1  | 	    "Content-Type" : [ "application/json" ]
mockServer_1  | 	  },
mockServer_1  | 	  "body" : "{\"test\":\"zażółć gęślą jaźń\"}"
mockServer_1  | 	}
```

**Comment by jamesdbloom** [comment] 2020-02-15 07:15
I’ll try to reproduce this locally and understand what is happening.

**Comment by jamesdbloom** [comment] 2020-02-16 14:21
The expectation initialiser does not contain a charset, therefore, it will be defaulting to `ISO-8859-1` as per the HTTP specification http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.7.1.  If you modify the initialiser as follows:

```javascript
[
  {
    "httpRequest": {
      "path": "/test",
      "method": "POST"
    },
    "httpResponse": {
      "statusCode": 200,
      "headers": [
        {
          "name": "Content-Type",
          "values": ["application/json; charset=utf-8"]
        }
      ],
      "body": "{\"test\":\"zażółć gęślą jaźń\"}"
    }
  }
]
```

The MockServer log then shows the initialiser is correct parsed:

```bash
2020-02-16 14:10:15  org.mockserver.log.MockServerEventLog  INFO  creating expectation:

	{
	  "id" : "e43e76b5-2aee-4086-af0c-c64eab4b472c",
	  "httpRequest" : {
	    "method" : "POST",
	    "path" : "/test"
	  },
	  "times" : {
	    "unlimited" : true
	  },
	  "timeToLive" : {
	    "unlimited" : true
	  },
	  "httpResponse" : {
	    "statusCode" : 200,
	    "headers" : {
	      "Content-Type" : [ "application/json; charset=utf-8" ]
	    },
	    "body" : "{\"test\":\"zażółć gęślą jaźń\"}"
	  }
	}
```

Then the following curl request shows that MockServer correctly reads the characters as `utf-8` and not `ISO-8859-1`.  This works in my case because I have saved the file as `utf-8` but if I have used a different character set for my local file I would need a different value in the `Content-Type` header.

```bash
$ curl -v -k https://localhost:1080/test --data '{"test":"zażółć gęślą jaźń"}' -H "Content-Type: application/json; charset=utf-8"

> POST /test HTTP/1.1
> Host: localhost:1080
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Type: application/json; charset=utf-8
> Content-Length: 37
> 

< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< connection: keep-alive
< content-length: 37
< 

{"test":"zażółć gęślą jaźń"}
```

The MockServer logs then show the following:

```bash
2020-02-16 14:17:25  org.mockserver.log.MockServerEventLog  INFO  received request:

	{
	  "method" : "POST",
	  "path" : "/test",
	  "headers" : {
	    "Host" : [ "localhost:1080" ],
	    "User-Agent" : [ "curl/7.64.1" ],
	    "Accept" : [ "*/*" ],
	    "Content-Type" : [ "application/json; charset=utf-8" ],
	    "Content-Length" : [ "37" ]
	  },
	  "keepAlive" : true,
	  "secure" : true,
	  "body" : {
	    "test" : "zażółć gęślą jaźń"
	  }
	}
 
2020-02-16 14:17:25  org.mockserver.log.MockServerEventLog  INFO  request:

	{
	  "method" : "POST",
	  "path" : "/test",
	  "headers" : {
	    "Host" : [ "localhost:1080" ],
	    "User-Agent" : [ "curl/7.64.1" ],
	    "Accept" : [ "*/*" ],
	    "Content-Type" : [ "application/json; charset=utf-8" ],
	    "Content-Length" : [ "37" ]
	  },
	  "keepAlive" : true,
	  "secure" : true,
	  "body" : {
	    "test" : "zażółć gęślą jaźń"
	  }
	}

 matched expectation:

	{
	  "id" : "82243b0f-f3a8-458a-bf33-184193692590",
	  "httpRequest" : {
	    "method" : "POST",
	    "path" : "/test"
	  },
	  "times" : {
	    "unlimited" : true
	  },
	  "timeToLive" : {
	    "unlimited" : true
	  },
	  "httpResponse" : {
	    "statusCode" : 200,
	    "headers" : {
	      "Content-Type" : [ "application/json; charset=utf-8" ]
	    },
	    "body" : "{\"test\":\"zażółć gęślą jaźń\"}"
	  }
	}
 
2020-02-16 14:17:25  org.mockserver.log.MockServerEventLog  INFO  returning response:

	{
	  "statusCode" : 200,
	  "headers" : {
	    "Content-Type" : [ "application/json; charset=utf-8" ]
	  },
	  "body" : "{\"test\":\"zażółć gęślą jaźń\"}"
	}

 for request:

	{
	  "method" : "POST",
	  "path" : "/test",
	  "headers" : {
	    "Host" : [ "localhost:1080" ],
	    "User-Agent" : [ "curl/7.64.1" ],
	    "Accept" : [ "*/*" ],
	    "Content-Type" : [ "application/json; charset=utf-8" ],
	    "Content-Length" : [ "37" ]
	  },
	  "keepAlive" : true,
	  "secure" : true,
	  "body" : {
	    "test" : "zażółć gęślą jaźń"
	  }
	}

 for action:

	{
	  "statusCode" : 200,
	  "headers" : {
	    "Content-Type" : [ "application/json; charset=utf-8" ]
	  },
	  "body" : "{\"test\":\"zażółć gęślą jaźń\"}"
	}
```

In addition, from the logs in the submitted issue, I can see the request also does not contain a character set, therefore, it will also be defaulting to `ISO-8859-1` as per the HTTP specification http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.7.1.  

Is the client sending the body using `ISO-8859-1`?  If not there is no way for MockServer to understand the character encoding of the request.

Can you please send the request with the character encoding explicitly specified to avoid relying on the HTTP default (which not all clients accurately implement).  This will ensure MockServer can correctly parse the request body.

I am going to close this issue but if once you have added a `charset` to the `content-type` you are still having issues please open a new issue.

**Closed by jamesdbloom** 2020-02-16 14:21 UTC
Labels: bug
