### ISSUE TITLE
ClassNotFoundException when using mvn with a submodule 

### ISSUE THREAD

**Issue by cosu** [mock-server/mockserver#201] opened 2015-11-23 12:35 UTC
I'm trying to use the maven integration to start a mock server instance before running integration test. My project uses a multi module structure  and surefire to run integration tests. The initialization code is executed correctly ( i see in the log the expectations being set) but when the test runs mockserver throws  a `ClassNotFoundException`:

```
[ERROR] ClassNotFoundException - while trying to instantiate ExceptionCallback class "eu.foo.bar.FooCallback"
java.lang.ClassNotFoundException: eu.foo.bar.FooCallback
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:260)
    at org.mockserver.mock.action.HttpCallbackActionHandler.instantiateCallback(HttpCallbackActionHandler.java:27)
    at org.mockserver.mock.action.HttpCallbackActionHandler.sendRequest(HttpCallbackActionHandler.java:48)
    at org.mockserver.mock.action.HttpCallbackActionHandler.handle(HttpCallbackActionHandler.java:22)
    at org.mockserver.mock.action.ActionHandler.processAction(ActionHandler.java:34)
    at org.mockserver.mockserver.MockServerHandler.channelRead0(MockServerHandler.java:169)
    at org.mockserver.mockserver.MockServerHandler.channelRead0(MockServerHandler.java:39)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:147)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
    at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:147)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at org.mockserver.server.unification.PortUnificationHandler.switchToHttp(PortUnificationHandler.java:109)
    at org.mockserver.server.unification.PortUnificationHandler.channelRead0(PortUnificationHandler.java:48)
    at org.mockserver.server.unification.PortUnificationHandler.channelRead0(PortUnificationHandler.java:28)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
```

Here is the [sample project](https://github.com/cosu/mstest) and the  [travis build log ](https://travis-ci.org/cosu/mstest/builds/92703531). 
Am I doing something completely wrong ?

**Comment by jamesdbloom** [comment] 2015-11-24 09:46
I'm not sure why you classes are not passed to the plugin classpath.  I explicityly add add classes from the test and main scopes (as this is not provided by default by maven).  It may help if you explicitly add your project as a dependency, as follows:

```xml
                <dependencies>
                    <dependency>
                        <groupId>eu.foo.bar</groupId>
                        <artifactId> integrationtests </artifactId>
                        <version>1.0-SNAPSHOT</version>
                    </dependency>
                </dependencies>
```

For a working example, you can look at the integration test: https://github.com/jamesdbloom/mockserver/blob/master/mockserver-maven-plugin-integration-tests/src/integration-tests/mockserver-initializer-test-classpath/pom.xml

**Comment by jamesdbloom** [comment] 2022-03-20 07:37
I think this issue is caused by the same problem at #464 so I'm closing this issue as the ClasspathLoader for MockServer launched by the maven plugin has been fixed and is in the SNAPSHOT release.

**Closed by jamesdbloom** 2022-03-20 07:37 UTC
Labels: bug
