### ISSUE TITLE
Test Flaky

### ISSUE THREAD

**Issue by shaker-project** [mock-server/mockserver#956] opened 2020-12-18 03:31 UTC
**Describe the issue**

Hello, we are a group of researchers interested in understanding methods to reduce costs associated with Test Flakiness [1]. We developed an approach to detect flaky tests, dubbed Shaker [2]. Shaker spawns stressor tasks in the running environment (e.g., tasks that consume lots of cpu or memory) to identify if perturbations can make tests fail.

We ran Shaker on mockserver project and found the following likely flaky test:

* shouldNotifyOnRemove - failed 1 time in 12 reruns.

[Denini](https://github.com/denini08), [Leopoldo](https://github.com/leopoldomt) and [Marcelo](https://github.com/damorim).

[1] https://hackernoon.com/flaky-tests-a-war-that-never-ends-9aa32fdef359

[2] D. Silva, L. Teixeira and M. d’Amorim, "Shake It! Detecting Flaky Tests Caused by Concurrency with Shaker," 2020 IEEE International Conference on Software Maintenance and Evolution (ICSME), Adelaide, Australia, 2020, pp. 301-311, https://ieeexplore.ieee.org/document/9240694/.

**MockServer version**
 5.11.2

**Comment by jamesdbloom** [comment] 2022-01-17 13:31
Thank you for the information I ran this test 100 times and couldn't reproduce so close this issue.

**Closed by jamesdbloom** 2022-01-17 13:31 UTC
