### ISSUE TITLE
Apparent incorrect communication through Forward Proxy

### ISSUE THREAD

**Issue by RafaelFont** [mock-server/mockserver#1168] opened 2022-02-02 10:36 UTC
We're using 5.10. We have the mock server client running as part of our system integration tests, which are run from Bamboo. We need to contact the mock server which is in AWS. For this, we need to pass through a corporate forward proxy.

We have found a problem, which is that we were getting 407  proxy authentication required, even though we had already provided the credentials.

In order to allow the client to connect through the forward proxy, we had to alter the following in NettyHTTPClient.java:

```
org.mockserver.client.NettyHttpClient.class
 public CompletableFuture<HttpResponse> sendRequest(final HttpRequest httpRequest, @Nullable InetSocketAddress remoteAddress, Integer connectionTimeoutMillis) throws SocketConnectionException {
        if (!eventLoopGroup.isShuttingDown()) {
           /*if (proxyConfiguration != null && proxyConfiguration.getType() == ProxyConfiguration.Type.HTTP) {
                remoteAddress = proxyConfiguration.getProxyAddress();
            } else if (remoteAddress == null) {*/
                remoteAddress = httpRequest.socketAddressFromHostHeader();
           // }
```

We commented out the conditions to allow the execution of _remoteAddress = httpRequest.socketAddressFromHostHeader();_

From our perspective we don't understand why the condition is there. We believe that proxyConfiguration.getProxyAddress(); will never work properly, because it provides the URL of the forward proxy, not the URL of the target host. 

We have checked the same code in 5.11.2, which is similar, and we have the same doubt.

We don't know if this is an issue or not, if it's general or not, but we had to make this change to make it work in our configuration, and we would like to better understand the reasoning behind this piece of code.

**Comment by jamesdbloom** [comment] 2022-02-02 20:27
@RafaelFont The remoteAddress is not a URL it is the TCP socket which the request is sent to.  When doing HTTP proxying (which is the not the same HTTPS or SOCKS) all that happens is the same request (i.e. the same Host header) is sent to the proxy. Which uses the Host header to determine where to forward the request.  If you look at the code inside the JDK for example when an HTTP proxy is configured that is what the JDK does.  It just updates the target TCP socket to the address (ip and port) of the proxy but otherwise sends the same request with the original Host header.

Can you please provide some more details about how you have configured the MockServerClient.  For example have you specified the address of the forward proxy and the credentials but are otherwise using the MockServer's ip and port for its address?  Does the forward proxy see the same ip and port for the MockServer, for example is there any NATing that would be translating the ip or port?

**Comment by lukaolidev** [comment] 2022-02-03 10:57
The MockServerClient is initialized and configured with proxy following way:

        _mockServerClient = new MockServerClient(mockServerHost, mockServerPortNum, CONTEXT_MOCKSERVER);
        if (proxyHost != null && proxyUser != null) {
            ProxyConfiguration proxyConfiguration = ProxyConfiguration.proxyConfiguration(ProxyConfiguration.Type.HTTP, 
                 String.format("%s:%s", proxyHost, proxyPort), proxyUser, proxyPassword);
            mockServerClient.setProxyConfiguration(proxyConfiguration);
        }_

In org.mockserver.client.NettyHttpClient.class we have commented out he remoteAddress assigning the ProxyAddress value

 _public CompletableFuture<HttpResponse> sendRequest(final HttpRequest httpRequest, @Nullable InetSocketAddress 
        remoteAddress, Integer connectionTimeoutMillis) throws SocketConnectionException {
        if (!eventLoopGroup.isShuttingDown()) {
           /*if (proxyConfiguration != null && proxyConfiguration.getType() == ProxyConfiguration.Type.HTTP) {
                remoteAddress = proxyConfiguration.getProxyAddress();
            } else if (remoteAddress == null) {*/
                remoteAddress = httpRequest.socketAddressFromHostHeader();
           // }_
 The remote address socket is used by Netty to create request as follows in HttpProxyHandler
 where the raddr is assigned remoteAddress (destinationAddress() is equal to remoteAddress)
 So the url and hostHeader are pointing to identical socket address (with format host:port) .
 that is the url and hostHeader properties of FullHttpRequest  have the same values and
for us the TCP tunneling via proxy server works correctly the if the remoteAddres is assing the address of target Server,
not the proxy address. My point is that remoteAddress must always have the value of httpRequest.socketAddressFromHostHeader() , no matter the proxyConfiguration exists or not,
otherwise if the remoteAddress is assign the  proxyConfiguration.getProxyAddress(), proxy forwarding to target server is
not working as expected. That is the reason we have commentedthat assigning out.  (seen above) 

    _protected Object newInitialMessage(ChannelHandlerContext ctx) throws Exception {
        InetSocketAddress raddr = destinationAddress();

        String hostString = HttpUtil.formatHostnameForHttp(raddr);
        int port = raddr.getPort();
        String url = hostString + ":" + port;
        String hostHeader = (ignoreDefaultPortsInConnectHostHeader && (port == 80 || port == 443)) ?
                hostString :
                url;

        FullHttpRequest req = new DefaultFullHttpRequest(
                HttpVersion.HTTP_1_1, HttpMethod.CONNECT,
                url,
                Unpooled.EMPTY_BUFFER, false);

        req.headers().set(HttpHeaderNames.HOST, hostHeader);

        if (authorization != null) {
            req.headers().set(HttpHeaderNames.PROXY_AUTHORIZATION, authorization);
        }

        if (outboundHeaders != null) {
            req.headers().add(outboundHeaders);
        }

        return req;
    }_

**Comment by jamesdbloom** [comment] 2022-02-03 22:19
The HttpProxyHandler is only used for HTTPS proxies, for HTTPS proxies an HTTP CONNECT request is sent first.  This is not used for HTTP proxies.  I can see from your configuration your using an HTTP proxy so the HttpProxyHandler doesn't get used.

I'm keen to help and understand you problem but I'm still confused about your configuration because it doesn't sound like any conventional proxying setup.  For HTTP proxies the socket address must always be the proxy otherwise the request would not be sent to the proxy.  Is your operation system or some other layer that MockServer is dependent on updating the request to send the TCP connection to the proxy.  This is the only way I could explain the behaviour although even this doesn't seem to make sense.

For HTTP proxy by definition the TCP connection goes to the proxy but the Host header points to the ultimate target (i.e. MockServer).  If the TCP connection is updated to point the ultimate target the the proxy is being by passed, unless AWS SDN or the Operation System or some other network layer is doing something strange to the traffic.

Can you not just using the address of MockServer as your proxy address in your configuration?

**Comment by jamesdbloom** [comment] 2022-03-22 21:40
I suspect this is the same issue as #1142 which has now been resolved and released so closing this issue.

**Closed by jamesdbloom** 2022-03-22 21:40 UTC
Labels: need_more_information

**Comment by lukaolidev** [comment] 2022-03-26 13:58
We have deployed the mockserver-war-5.10.0.war file and it is returning the response status code 500 Internal Server Error.
We would like to configure the logger with log file to pinpoint the cause . Unfortunately , we did not find any documentation referring this issue.  Your advice would be appreciated.
