### ISSUE TITLE
404 when request has Content-Type application/json

### ISSUE THREAD

**Issue by rebekevsha** [mock-server/mockserver#1118] opened 2022-01-14 17:22 UTC
**Describe the issue**
I create a expectation with httpResponseTemplate and try to map some parameter from request.body to response.body. But if I put -H 'Content-Type: application/json' in curl -X POST 'https://localhost:9000/some/path' i have 404 error. But it still working when i put Content-Type: text/plain. I Think that parser working not correct.

**MockServer version**
5.11.1

**To Reproduce**
Steps to reproduce the issue:

1. Docker
2. 
   ```bash
   curl -X PUT 'https://localhost:9000/mockserver/expectation' \
   -H 'Content-Type: application/json' \
   --data-raw '{
       "httpRequest": {
           "path": "/some/path",
           "body" : {
                 "type" : "JSON"
           }
       },
       "httpResponseTemplate": {
           "template": "return { statusCode: 200, headers: { Date: [ Date() ] }, body: JSON.stringify({is_active: JSON.parse(request.body.string).is_active, id: \"1234\", name: \"taras\"}) };",
           "templateType": "JAVASCRIPT"
       }
   }
   ```
   ```bash
   curl -X POST 'https://localhost:9000/some/path' -H 'Content-Type: application/json' --data-raw '{
       "is_active": false
   }'
   ```

3. Response Status code - 404

**Expected behaviour**
Response status code - 200
Response body - `{"is_active":false,"id":"1234","name":"taras"}`

**MockServer Log**
```
2022-01-14T17:20:18.093056555ZCaused by: <eval>:3 SyntaxError: Invalid JSON: <json>:1:0 Expected json literal but found uInfo2022-01-14T17:20:18.093061903ZundefinedInfo2022-01-14T17:20:18.093067586Z^Info2022-01-14T17:20:18.093072979Z
at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
Info2022-01-14T17:20:18.093078138Z
at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.syntaxError(ECMAErrors.java:160)
Info2022-01-14T17:20:18.093083427Z
at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.syntaxError(ECMAErrors.java:145)
Info2022-01-14T17:20:18.093089058Z
at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.JSONFunctions.parse(JSONFunctions.java:81)
2022-01-14T17:20:18.093095463Z
at jdk.scripting.nashorn/jdk.nashorn.internal.objects.NativeJSON.parse(NativeJSON.java:118)
Info2022-01-14T17:20:18.093106329Z
at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$309$\^eval\_/0x00000001004bc440.handle(<eval>:3)
Info2022-01-14T17:20:18.093111792Z
at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$311$196A$\^eval\_/0x00000001004c9840.serialise(<eval>:4)
Info2022-01-14T17:20:18.093117109Z
at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:657)
Info2022-01-14T17:20:18.093122095Z
at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
Info2022-01-14T17:20:18.093127121Z
at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
Info2022-01-14T17:20:18.093132135Z
at jdk.scripting.nashorn/jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:120)
Info2022-01-14T17:20:18.093137469Z
at org.mockserver.templates.engine.javascript.JavaScriptTemplateEngine.executeTemplate(JavaScriptTemplateEngine.java:56)
Info2022-01-14T17:20:18.093143186Z ... 54 more**2022-01-14T17:20:18.093148477ZCaused by: jdk.nashorn.internal.runtime.ParserException: <json>:1:0 Expected json literal but found u**Info2022-01-14T17:20:18.093153672ZundefinedInfo2022-01-14T17:20:18.093158909Z^Info2022-01-14T17:20:18.093164313Z
at jdk.scripting.nashorn/jdk.nashorn.internal.parser.JSONParser.error(JSONParser.java:529)
Info2022-01-14T17:20:18.093169494Z
at jdk.scripting.nashorn/jdk.nashorn.internal.parser.JSONParser.error(JSONParser.java:533)
Info2022-01-14T17:20:18.093174575Z
at jdk.scripting.nashorn/jdk.nashorn.internal.parser.JSONParser.expectedError(JSONParser.java:541)
Info2022-01-14T17:20:18.093180048Z
at jdk.scripting.nashorn/jdk.nashorn.internal.parser.JSONParser.parseLiteral(JSONParser.java:182)
Info2022-01-14T17:20:18.093185394Z
at jdk.scripting.nashorn/jdk.nashorn.internal.parser.JSONParser.parse(JSONParser.java:148)
Info2022-01-14T17:20:18.093190947Z
at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.JSONFunctions.parse(JSONFunctions.java:79)
```

**Comment by jamesdbloom** [comment] 2022-01-28 20:26
@rebekevsha  the problem is in the code in the template, if you want to query the value from a json body you need to use the following syntax.  I agree sadly this is not as clear as it should be and perhaps all BodyDTOs should have a common field, but currently that isn't the case.  So that means if the body is a string body then it has a field called `string` which is a string value containing JSON.  So the JSON.parse(...) method works.  If the body is a JSON then is has a field called `json` is an object.

```json
{
    "httpRequest": {
        "path": "/some/path", 
        "body": {
            "type": "JSON"
        }
    }, 
    "httpResponseTemplate": {
        "template": "return { statusCode: 200, headers: { Date: [ Date() ] }, body: JSON.stringify({is_active: request.body.json.is_active, id: \"1234\", name: \"taras\"}) };", 
        "templateType": "JAVASCRIPT"
    }
}
```

I'm going to close this issue but add an item to the backlog to improve the clarity of the object model for JS templates: https://trello.com/c/UO5jiX0g/165-improve-the-clarity-of-the-object-model-for-js-templates

**Comment by jamesdbloom** [comment] 2022-01-28 21:51
I've improved the format somewhat by adding an additional field to the request called bodyAsString, this means you can always guarantee this field existing and should return some thing more stable and common for example for a JSON body is returns the JSON as a string and for a string is returns the JSON as a string, for the following then works in both the examples you provided:

```json
{
    "httpRequest": {
        "path": "/some/path", 
        "body": {
            "type": "JSON"
        }
    }, 
    "httpResponseTemplate": {
        "template": "return { statusCode: 200, headers: { Date: [ Date() ] }, body: JSON.stringify({is_active: JSON.parse(request.bodyAsString).is_active, id: \"1234\", name: \"taras\"}) };", 
        "templateType": "JAVASCRIPT"
    }
}
```

I'm going to re-open this issue as a documentation issue to add documentation about this new field and some more examples to the documentation.

**Closed** 2022-01-28 23:57 UTC
Labels: documentation, next
