### ISSUE TITLE
Mockserver randomly logging requests multiple times from 5.7.2

### ISSUE THREAD

**Issue by scierniak** [mock-server/mockserver#691] opened 2019-11-22 22:55 UTC
Similar to issue #685 but with version 5.7.2

We noticed some random requests are logged multiple times. I found one logged 6 times.

Env of execution:
- Docker version with version 5.7.2
- cmd line: java -Xms4G -Xmx7G -Dmockserver.initializationJsonPath='/etc/mockserver/mockserver-expectations.json' -Dmockserver.maxLogEntries='2000' -Dfile.encoding=UTF-8 -jar /opt/mockserver/mockserver-netty-jar-with-dependencies.jar  -serverPort 1080 -logLevel WARN

I was not able to reproduce it locally

example of a request:
```
{
  "method" : "POST",
  "path" : "/object/I0007",
  "headers" : {
    "Api-Version" : [ "1.0" ],
    "Correlation-Id" : [ "000000000187" ],
    "Generation-Time" : [ "2019-11-22T15:59:08.549Z" ],
    "Transmission-Time" : [ "2019-11-22T15:59:08.540Z" ],
    "Host" : [ "localhost" ],
    "Accept-Encoding" : [ "gzip, deflate" ],
    "Connection" : [ "close" ],
    "Content-Type" : [ "application/json" ],
    "Content-Length" : [ "324" ]
  },
  "keepAlive" : false,
  "secure" : false,
  "body" : {
    "type" : "STRING",
    "string" : "{\"generationTime\": \"2019-11-22T15:59:08.547Z\", \"key1\": \"value1\"}",
    "contentType" : "application/json"
  }
}
```
Regards

**Comment by jamesdbloom** [comment] 2019-11-23 01:35
Please submit a log showing this detail because unfortunately without that detail it will not be possible to work out if / where the problem is.

**Comment by jamesdbloom** [comment] 2019-12-01 07:38
@scierniak is there any update on this?

**Comment by scierniak** [comment] 2019-12-09 19:58
Trying to reproduce with more logs, but got completely confused by data returned by "/mockserver/retrieve?type=logs". 

Time of logs are not in order:
        Line 32111: 2019-12-09 16:31:58 - returning response:
	Line 32162: 2019-12-09 18:26:02 - verifying requests that match:
	Line 32175: 2019-12-09 18:26:14 - request not found exactly once, expected:
	Line 32386: 2019-12-09 18:26:14 - verifying requests that match:
	Line 32399: 2019-12-09 18:26:14 - returning response:
	Line 32449: 2019-12-09 18:26:14 - received request:
	Line 32480: 2019-12-09 18:26:14 - request not found exactly once, expected:
	Line 32691: 2019-12-09 18:26:14 - verifying requests that match:
	Line 32704: 2019-12-09 18:26:14 - clearing logs that match:
	Line 32712: 2019-12-09 16:32:12 - received request:
	Line 32742: 2019-12-09 16:32:12 - request not found exactly once, expected:
	Line 32953: 2019-12-09 16:32:12 - verifying requests that match:
	Line 32966: 2019-12-09 16:32:12 - returning response:
	Line 33016: 2019-12-09 18:26:14 - received request:
	Line 33046: 2019-12-09 18:26:14 - request not found exactly once, expected:
	Line 33257: 2019-12-09 18:26:14 - verifying requests that match:
	Line 33270: 2019-12-09 18:26:14 - returning response:
	Line 33320: 2019-12-09 16:32:12 - received request:
	Line 33351: 2019-12-09 16:32:12 - request not found exactly once, expected:
	Line 33562: 2019-12-09 16:32:12 - verifying requests that match:
	Line 33575: 2019-12-09 16:32:12 - returning response:


Even when clearing, I found old logs.

**Comment by jamesdbloom** [comment] 2019-12-09 21:21
There was a bug with the serialising of the date-time stamp which was already fixed.  Please use the latest version of MockServer, however, the order is correct it is just the date-time stamp which is wrong and it can be ignored.  I am surprised to see SEVERE logs have you shown the full log because most of the relevant information seems to be missing.

**Comment by scierniak** [comment] 2019-12-18 15:45
As workaround, we installed back version 5.7.0 where we don't see this issue happening

**Comment by jamesdbloom** [comment] 2020-01-31 06:53
Closing issue as can't reproduce in the current codebase and no further information provided to help debug if there is a problem or not.

**Closed by jamesdbloom** 2020-01-31 06:53 UTC
Labels: need_more_information, unable_to_reproduce
